FROM node:10

# Set environment variables
ENV appDir /app

# Set the work directory
RUN mkdir -p /app
WORKDIR ${appDir}

# Install dev dependencies
RUN apt-get update && apt-get upgrade -y

#Expose the port
EXPOSE 3000

ENTRYPOINT sleep infinity
