# This is the docker-compose file that includes the PDD backend and a postgres db for it.
# The PDD backend will likely be merged with terraware-server some day, and this file can go away
version: '3.8'

services:
  postgres:
    image: 'postgis/postgis:13-3.3'
    ports:
      - '5432:5432'
    volumes:
      - '$HOME/docker/volumes/postgres/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'terraware'
      POSTGRES_PASSWORD: 'terraware'

  terraware-server:
    image: 'terraware/terraware-server:STAGING'
    ports:
      - '8080:8080'
    environment:
      - 'DATABASE_URL=jdbc:postgresql://postgres:5432/terraware'
      - 'DATABASE_PASSWORD=terraware'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET'
      - 'SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI'
      - 'SPRING_THYMELEAF_PREFIX=classpath:templates'
      - 'TERRAWARE_MAPBOX_API_TOKEN'
      - 'TERRAWARE_PHOTO_DIR=/photos'
      - 'TERRAWARE_ENABLE_AWAITING_CHECK_IN=true'
      - 'TERRAWARE_ALLOW_ADMIN_UI_FOR_NON_ADMINS=true'
    volumes:
      - './photo-data:/photos'
    depends_on:
      - 'postgres'

  pdd-postgres:
    image: 'postgres:14'
    ports:
      - '5433:5433'
    command: -p 5433
    volumes:
      - '$HOME/docker/volumes/pdd-postgres/data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'pdd'
      POSTGRES_PASSWORD: 'pdd'

  pdd-backend:
    image: 'TODO.dkr.ecr.us-west-2.amazonaws.com/pdd-backend:staging'
    ports:
      - '8081:8080'
    environment:
      - 'DATABASE_URL=jdbc:postgresql://pdd-postgres:5433/pdd'
      - 'DATABASE_PASSWORD=pdd'
      - 'SPRING_PROFILES_ACTIVE=staging'
      - 'PDD_MEDIADIR=/photos'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID'
      - 'SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI'
    volumes:
      - './pdd-photo-data:/photos'
    depends_on:
      - 'pdd-postgres'
