const eslint = require('@eslint/js');
const tsparser = require('@typescript-eslint/parser');
const eslintjsdoc = require('eslint-plugin-jsdoc');
const eslintpreferarrow = require('eslint-plugin-prefer-arrow');
const eslintreact = require('eslint-plugin-react');
const tseslint = require('typescript-eslint');

module.exports = tseslint.config(
  {
    files: ['**/*.ts', '**/*.tsx'],
    ignores: ['**/*.js', '*.js', '*.json'],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: {
      // react: eslintreact,
      jsdoc: eslintjsdoc,
      'prefer-arrow': eslintpreferarrow,
    },
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
        project: './tsconfig.json',
        settings: {
          react: {
            version: '18',
          },
        },
      },
    },
    rules: {
      '@typescript-eslint/adjacent-overload-signatures': 'error',
      '@typescript-eslint/array-type': [
        'error',
        {
          default: 'array',
        },
      ],
      '@typescript-eslint/ban-ts-comment': 'error',
      // '@typescript-eslint/ban-types': [
      //   'error',
      //   {
      //     types: {
      //       Object: {
      //         message: 'Avoid using the `Object` type. Did you mean `object`?',
      //       },
      //       Function: {
      //         message: 'Avoid using the `Function` type. Prefer a specific function type, like `() => void`.',
      //       },
      //       Boolean: {
      //         message: 'Avoid using the `Boolean` type. Did you mean `boolean`?',
      //       },
      //       Number: {
      //         message: 'Avoid using the `Number` type. Did you mean `number`?',
      //       },
      //       String: {
      //         message: 'Avoid using the `String` type. Did you mean `string`?',
      //       },
      //       Symbol: {
      //         message: 'Avoid using the `Symbol` type. Did you mean `symbol`?',
      //       },
      //     },
      //   },
      // ],
      '@typescript-eslint/consistent-type-assertions': 'error',
      '@typescript-eslint/dot-notation': 'error',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      // '@typescript-eslint/indent': ['error', 2],
      // '@typescript-eslint/member-delimiter-style': [
      //   'error',
      //   {
      //     multiline: {
      //       delimiter: 'semi',
      //       requireLast: true,
      //     },
      //     singleline: {
      //       delimiter: 'semi',
      //       requireLast: false,
      //     },
      //   },
      // ],
      '@typescript-eslint/naming-convention': [
        'off',
        {
          selector: 'variable',
          format: ['camelCase', 'UPPER_CASE', 'PascalCase'],
          leadingUnderscore: 'allow',
          trailingUnderscore: 'forbid',
        },
      ],
      '@typescript-eslint/no-array-constructor': 'error',
      '@typescript-eslint/no-duplicate-enum-values': 'error',
      '@typescript-eslint/no-empty-function': 'error',
      '@typescript-eslint/no-empty-interface': 'error',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-extra-non-null-assertion': 'error',
      '@typescript-eslint/no-loss-of-precision': 'error',
      '@typescript-eslint/no-misused-new': 'error',
      '@typescript-eslint/no-namespace': 'error',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
      '@typescript-eslint/no-parameter-properties': 'off',
      '@typescript-eslint/no-shadow': [
        'error',
        {
          hoist: 'all',
        },
      ],
      '@typescript-eslint/no-this-alias': 'error',
      '@typescript-eslint/no-unnecessary-type-constraint': 'error',
      '@typescript-eslint/no-unsafe-declaration-merging': 'error',
      '@typescript-eslint/no-unused-expressions': 'error',
      '@typescript-eslint/no-unused-vars': 'error',
      '@typescript-eslint/no-use-before-define': 'off',
      '@typescript-eslint/no-var-requires': 'error',
      '@typescript-eslint/prefer-as-const': 'error',
      '@typescript-eslint/prefer-for-of': 'error',
      '@typescript-eslint/prefer-function-type': 'error',
      '@typescript-eslint/prefer-namespace-keyword': 'error',
      // '@typescript-eslint/quotes': [
      //   'error',
      //   'single',
      //   {
      //     avoidEscape: true,
      //   },
      // ],
      '@typescript-eslint/require-await': 'error',
      // '@typescript-eslint/semi': ['error', 'always'],
      '@typescript-eslint/triple-slash-reference': [
        'error',
        {
          path: 'always',
          types: 'prefer-import',
          lib: 'always',
        },
      ],
      '@typescript-eslint/typedef': 'off',
      '@typescript-eslint/unified-signatures': 'error',
      'arrow-parens': ['error', 'always'],
      'brace-style': ['off', 'off'],
      complexity: 'off',
      'constructor-super': 'error',
      curly: 'error',
      'dot-notation': 'off',
      eqeqeq: ['error', 'always'],
      'for-direction': 'error',
      'getter-return': 'error',
      'guard-for-in': 'error',
      'id-denylist': [
        'error',
        'any',
        'Number',
        'number',
        'String',
        'string',
        'Boolean',
        'boolean',
        'Undefined',
        'undefined',
      ],
      'id-match': 'error',
      'jsdoc/check-alignment': 'error',
      'jsdoc/check-indentation': 'error',
      // 'jsdoc/newline-after-description': 'error',
      'linebreak-style': ['error', 'unix'],
      'max-classes-per-file': ['error', 1],
      'new-parens': 'error',
      'no-array-constructor': 'off',
      'no-async-promise-executor': 'error',
      'no-bitwise': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-console': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-function': 'off',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'off',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-invalid-this': 'off',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'off',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-new-wrappers': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-octal': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow': 'off',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-throw-literal': 'error',
      'no-trailing-spaces': [
        'error',
        {
          skipBlankLines: true,
        },
      ],
      'no-undef': 'warn',
      'no-undef-init': 'error',
      'no-underscore-dangle': 'off',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-expressions': 'off',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'warn',
      'no-use-before-define': 'off',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-var': 'error',
      'no-with': 'error',
      'object-shorthand': 'error',
      'one-var': ['error', 'never'],
      'padded-blocks': [
        'off',
        {
          blocks: 'never',
        },
        {
          allowSingleLineBlocks: true,
        },
      ],
      'prefer-arrow/prefer-arrow-functions': [
        'error',
        {
          allowStandaloneDeclarations: true,
        },
      ],
      'prefer-const': 'error',
      radix: 'error',
      // 'react/display-name': 'error',
      // 'react/jsx-boolean-value': 'off',
      // 'react/jsx-key': 'error',
      // 'react/jsx-no-bind': 'off',
      // 'react/jsx-no-comment-textnodes': 'error',
      // 'react/jsx-no-duplicate-props': 'error',
      // 'react/jsx-no-target-blank': 'error',
      // 'react/jsx-no-undef': 'error',
      // 'react/jsx-tag-spacing': [
      //   'off',
      //   {
      //     afterOpening: 'allow',
      //     closingSlash: 'allow',
      //   },
      // ],
      // 'react/jsx-uses-react': 'error',
      // 'react/jsx-uses-vars': 'error',
      // 'react/no-children-prop': 'error',
      // 'react/no-danger-with-children': 'error',
      // 'react/no-deprecated': 'error',
      // 'react/no-direct-mutation-state': 'error',
      // 'react/no-find-dom-node': 'error',
      // 'react/no-is-mounted': 'error',
      // 'react/no-render-return-value': 'error',
      // 'react/no-string-refs': 'error',
      // 'react/no-unescaped-entities': 'error',
      // 'react/no-unknown-property': 'error',
      // 'react/no-unsafe': 'off',
      // 'react/prop-types': 'error',
      // 'react/react-in-jsx-scope': 'error',
      // 'react/require-render-return': 'error',
      // 'react/self-closing-comp': 'error',
      'require-await': 'off',
      'require-yield': 'error',
      'space-in-parens': ['off', 'never'],
      'spaced-comment': [
        'error',
        'always',
        {
          markers: ['/'],
        },
      ],
      'use-isnan': 'error',
      'valid-typeof': 'off',
      // '@typescript-eslint/tslint/config': [
      //   'error',
      //   {
      //     rules: {
      //       'array-bracket-spacing': [true, 'never'],
      //       'brace-style': [
      //         true,
      //         '1tbs',
      //         {
      //           allowSingleLine: true,
      //         },
      //       ],
      //       'handle-callback-err': [true, '^(e|err|error)$'],
      //       'jsx-no-string-ref': true,
      //       'no-ex-assign': true,
      //       'ter-arrow-spacing': true,
      //       'ter-no-mixed-spaces-and-tabs': true,
      //       'ter-prefer-arrow-callback': true,
      //       whitespace: true,
      //     },
      //   },
      // ],
    },
  }
);
