import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
  en: {
    CANCEL: 'Cancel',
    SAVE: 'Save',
    SAVE_CHANGES: 'Save Changes',
    GENERIC_ERROR: 'An error occurred',
    PREEXISTING_SPECIES: 'This species already exists',
    DELETE: 'Delete',
    SPECIES_NAME: 'Species Name',
    DASHBOARD: 'Dashboard',
    DELETE_SPECIES: 'Delete Species',
    DELETE_CONFIRMATION_MODAL_MAIN_TEXT:
      'Are you sure you want to delete your selected species? This will delete them from your list, but you’ll keep all data attached to existing entries.',
    SNACKBAR_MSG_NEW_SPECIES_ADDED: 'New species added just now.',
    SNACKBAR_MSG_CHANGES_SAVED: 'Changes saved just now.',
    SNACKBAR_MSG_SPECIES_DELETED: 'Species deleted just now.',
    SNACKBAR_MSG_PLANT_DELETED: 'Plant deleted just now.',
    EDIT_SPECIES: 'Edit Species',
    ADD_SPECIES: 'Add Species',
    IMPORT_SPECIES: 'Import Species',
    ADD: 'Add',
    NEW_SPECIES: 'New Species',
    SPECIES: 'Species',
    AS_OF: 'As of',
    OTHER: 'Other',
    LOGOUT: 'Logout',
    DATE: 'Date',
    NOTES: 'Notes',
    EXISTING_SPECIES_MSG: '“{0}” is already in your species list. ',
    CREATE_NEW_SPECIES: 'Create New Species',
    TOTAL: 'Total',
    FILTERS: 'Filters',
    FROM: 'From',
    TO: 'To',
    APPLY_FILTERS: 'Apply Filters',
    CLEAR_FILTERS: 'Clear Filters',
    GROWTH_SINCE_LAST_WEEK: '{0}% since last week',
    LOADING: 'Loading...',
    PROJECTS: 'Projects',
    PROJECT: 'Project',
    SEEDS: 'Seeds',
    ACCESSIONS: 'Accessions',
    OR: 'OR',
    FLORA: 'Flora',
    SEED_COLLECTION: 'Seed Collection',
    PROCESSING_AND_DRYING: 'Processing & Drying',
    STORAGE: 'Storage',
    WITHDRAWAL: 'Withdrawal',
    CREATE: 'Create',
    SAVING: 'Saving...',
    CREATE_ACCESSION: 'Create Accession',
    CHANGES_SAVED: 'Changes Saved!',
    GERMINATION_TESTING: 'Germination Testing',
    NURSERY: 'Nursery',
    LAB: 'Lab',
    SAVE_ACCESSION_ERROR: 'An error occurred when saving the accession.',
    GET_ACCESSION_ERROR: 'An error occurred when getting the accession.',
    START: 'Start',
    END: 'End',
    SEARCH: 'Search',
    YES: 'Yes',
    NO: 'No',
    ACCESSION: 'Accession',
    STATUS: 'Status',
    RECEIVED_DATE: 'Received Date',
    COLLECTED_DATE: 'Collected Date',
    SITE_LOCATION: 'Site Location',
    ENDANGERED: 'Endangered',
    RARE: 'Rare',
    RARE_ENDANGERED: 'Rare, Endangered',
    NUMBER_OF_TREES: 'Number of Trees',
    ESTIMATED_SEEDS_INCOMING: 'Estimated Seeds Incoming',
    LANDOWNER: 'Landowner',
    PROCESSING_START_DATE: 'Processing Start Date',
    SEEDS_TOTAL: 'Quantity of Seeds',
    SEEDS_UNITS: 'Units Quantity of Seeds',
    DRYING_START_DATE: 'Drying Start Date',
    PROCESSING_METHOD: 'Processing Method',
    DRYING_END_DATE: 'Estimated Drying End Date',
    SEEDS_REMAINING: 'Seeds Remaining',
    REMAINING_UNITS: 'Remaining Units',
    STORING_START_DATE: 'Storing Start Date',
    STORAGE_CONDITION: 'Storage Condition',
    STORAGE_LOCATION: 'Storage Location',
    NUMBER_OF_STORAGE_PACKETS: 'Number of Storage Packets',
    DATE_OF_WITHDRAWAL: 'Date of Withdrawal',
    NUMBER_OF_SEEDS_WITHDRAWN: 'Seeds Withdrawn',
    DESTINATION: 'Destination',
    NUMBER_OF_SEEDS_REMAINING: 'Seeds Remaining',
    PURPOSE: 'Purpose',
    TARGET_RH: 'Target %RH',
    GERMINATION_TEST_TYPE: 'Germination Test Type',
    GERMINATION_TREATMENT: 'Germination Treatment',
    SEED_TYPE: 'Seed Type',
    NUMBER_OF_SEEDS_FILLED: 'Number of Seeds Filled',
    GERMINATION_START_DATE: 'Germination Start Date',
    NUMBER_OF_SEEDS_SOWN: 'Number of Seeds Sown',
    TOTAL_OF_SEEDS_GERMINATED: 'Total of Seeds Germinated',
    NUMBER_OF_SEEDS_EMPTY: 'Number of Seeds Empty',
    MOST_RECENT_GERMINATION_TEST_DATE: 'Most Recent Germination Test Date',
    PERCENTAGE_VIABILITY: '% Viability',
    GEMRINATION_SUBSTRATE: 'Germination Substrate',
    NUMBER_OF_SEEDS_COMPROMISED: 'Number of Seeds Compromised',
    MOST_RECENT_PERCENTAGE_VIABILITY: 'Most Recent % Viability',
    TOTAL_ESTIMATED_PERCENTAGE_VIABILITY: 'Total Estimated % Viability',
    BAG_IDS: 'Bag IDs',
    REPORT: 'Report',
    DOWNLOAD_REPORT_DESCRIPTION:
      'You are about to download this datatable as a report. This csv file can be found in your Downloads. Please name your report below.',
    BOTH_WITHDRAWS_DESCRIPTION:
      'You have withdrawn seeds by both count and weight. As a result, the app has calculated the amount of seeds withdrawn for you by weight.',
    REPORT_NAME: 'Report Name',
    DOWNLOAD: 'Download',
    ADD_COLUMNS: 'Add columns',
    ADD_COLUMNS_DESCRIPTION: 'Select columns you want to add. Deselect columns you want to remove.',
    CLEAR: 'Clear',
    NEW_ENTRY: 'New Entry',
    SEE_ENTRIES: 'See Entries',
    TOTAL_SEEDS_GERMINATED: 'Total Seeds Germinated',
    TOTAL_ESTIMATED_VIABILITY: 'Total Estimated Viability',
    LAB_DESCRIPTION: 'All the details about lab germination tests conducted on the seeds.',
    NEW_TEST: 'New Test',
    CUT_TEST: 'Cut Test',
    FILLED_SEEDS: 'Filled Seeds',
    EMPTY_SEEDS: 'Empty Seeds',
    COMPROMISED_SEEDS: 'Compromised Seeds',
    SEEDS_GERMINATED: 'Seeds Germinated',
    SEEDS_GERMINATED_LC: 'seeds germinated',
    RECORDING_DATE: 'Recording Date',
    CREATE_ENTRY: 'Create Entry',
    SCHEDULE_DATE_INFO: 'Schedule a date by selecting a future date.',
    START_DATE: 'Start Date',
    END_DATE: 'End Date',
    FRESH_SEEDS: 'Fresh Seeds',
    STORED_SEEDS: 'Stored Seeds',
    NURSERY_MEDIA: 'Nursery Media',
    AGAR_PETRI_DISH: 'Agar Petri Dish',
    PAPER_PETRI_DISH: 'Paper Petri Dish',
    SOAK: 'Soak',
    SCARIFY: 'Scarify',
    GA3: 'GA3',
    STRATIFICATION: 'Stratification',
    SEEDS_SOWN: 'Seeds Sown',
    STAFF_RESPONSIBLE: 'Staff Responsible',
    CREATE_TEST: 'Create Test',
    SUBSTRATE: 'Substrate',
    TREATMENT: 'Treatment',
    SOWN: 'Sown',
    REMAINING: 'Remaining',
    STAFF: 'Staff',
    GERMINATED: 'Germinated',
    COLLECTED_ON: 'Collected On',
    RECEIVED_ON: 'Received On',
    NO_FUTURE_DATES: 'No future dates allowed',
    NO_NEGATIVE_NUMBERS: 'No negative numbers allowed',
    SEED_COLLECTION_DESCRIPTION: 'All the details about the species, date collected, collectors and the site location.',
    FAMILY: 'Family',
    FOUNDER_ID: 'Founder ID',
    FIELD_NOTES: 'Field Notes',
    FIELD_NOTES_PLACEHOLDER: 'Important notes about seeds, fruits, or plants',
    PRIMARY_COLLECTOR: 'Primary Collector',
    SITE: 'Site',
    FACILITY: 'Facility',
    ENVIRONMENTAL_NOTES: 'Environmental Notes',
    ENVIRONMENTAL_NOTES_PLACEHOLDER: 'Important notes about landscape, climate, and environmental conditions',
    NEW_ACCESSION: 'Add Accession',
    NEW_ACCESSION_DESCRIPTION: 'An accession number will be generated once you create the accession.',
    NEW_ACCESSION_INFO:
      'Information like Seed Bags, Photos and Geolocations can only be added via the Seed Collector Android app. All the other information about processing, drying, storage and withdrawals can be added after first creating the accession.',
    SEED_BAGS: 'Seed Bags',
    PHOTOS: 'Photos',
    GEOLOCATIONS: 'Geolocations',
    NEXT_PROCESSING_AND_DRYING: 'Next: Processing & Drying',
    UNSURE: 'Unsure',
    ACCESSION_SAVED: 'Accession saved',
    ADD_NEW: 'Add New',
    NURSERY_DESCRIPTION: 'All the details about nursery germination tests conducted on the seeds.',
    PROCESSING_AND_DRYING_DESCRIPTION: 'All the details about processing and drying the seeds.',
    QUANTIFY: 'Quantify',
    SEED_WEIGHT: 'Seed Weight',
    SEED_COUNT: 'Seed Count',
    SUBSET_WEIGHT: 'Weight of Seed Subset',
    NUMBER_OF_SEEDS_IN_SUBSET: '# of Seeds in Subset',
    TOTAL_WEIGHT_OF_SEEDS: 'Total Weight of Seeds',
    TOTAL_SEEDS_COUNT_ESTIMATION: 'Total Seeds Count Estimation',
    VIABILITY_TEST_TYPES: 'Viability Test Types',
    VIABILITY_TEST_TYPE: 'Viability Test Type',
    VIABILITY_TEST_TYPES_INFO:
      'Selecting either one will unlock a new option on the sidebar after you save the changes.',
    NURSERY_GERMINATION: 'Nursery Germination',
    LAB_GERMINATION: 'Lab Germination',
    ESTIMATED_DRYING_END_DATE: 'Estimated Drying End Date',
    SCHEDULE_DATE_TO_MOVE: 'Schedule Date to Move from Racks to Dry Cabinets',
    IF_APPLIES: 'Only if it applies',
    PROCESSING_AND_DRYING_INFO:
      'By adding information about processing/drying and saving changes, you will be automatically changing this accession’s stage from Pending to either Processing, Processed, Drying, or Dried, depending on the information you fill in.',
    NEXT_STORING: 'Next: Storing',
    STORAGE_DESCRIPTION: 'All the details about storing the seeds.',
    STARTING_ON: 'Starting On',
    NUMBER_OF_PACKETS: 'Number of Packets',
    STORAGE_INFO:
      'By adding information about storage and saving changes, you will be automatically changing this accession’s stage from Pending to Stored.',
    NEXT_WITHDRAWAL: 'Next: Withdrawal',
    LOCATION: 'Location',
    CONDITION: 'Condition',
    SUMMARY: 'Summary',
    WELCOME_MSG: 'Welcome and happy seeding!',
    ACTIVE_ACCESSIONS: 'Active Accessions',
    MOST_RECENT_STAGE_UPDATES: 'Most Recent Stage Updates',
    PENDING_UPDATES:
      'There are {0} seed collection bags have been waiting since drop off for at least 1 week and are ready to be processed.',
    PROCESSED_UPDATES:
      '{0} accessions have finished processing for at least 2 weeks and are ready to be tested for %RH (or dried).',
    DRIED_UPDATES: '{0} accessions have past its drying end date and are ready to be stored.',
    WITHDRAWN_UPDATES: '{0} accessions have been completely withdrawn this week and are now inactive.',
    WITHDRAWAL_DESCRIPTION: 'All the details about withdrawal of the seeds.',
    ALL_SEEDS_WITHDRAWN_MSG:
      "As all seeds have been withdrawn, new withdrawals are disabled, the accession's stage has been set to Withdrawn, and the accession itself marked as Inactive",
    INITIAL_SEEDS: 'Initial Seeds',
    SEEDS_WITHDRAWN: 'Seeds Withdrawn',
    SEEDS_WITHDRAWN_UNITS: 'Seeds Withdrawn Units',
    WITHDRAW_REMAINING_SEEDS: 'Withdraw All Remaining Seeds',
    ZERO: 'zero',
    AVAILABLE: 'available',
    NEW_WITHDRAWAL: 'New Withdrawal',
    WITHDRAWN: 'Withdrawn',
    SCHEDULE_WITHDRAWAL: 'Schedule Withdrawal',
    SCHEDULED: '(Scheduled)',
    SCHEDULING_FOR: 'Scheduling for: {0}',
    WITHDRAW_SEEDS: 'Withdraw seeds',
    WITHDRAWN_ON: 'Withdrawn On',
    PROPAGATION: 'Propagation',
    OUTREACH_OR_EDUCATION: 'Outreach or Education',
    RESEARCH: 'Research',
    BROADCAST: 'Broadcast',
    SHARE_WITH_ANOTHER_SITE: 'Share with another Site',
    SCHEDULED_FOR: 'Scheduled for',
    ALERTS: 'Alerts',
    EDIT_SPECIES_MODAL_QUESTION: 'Would you like to apply this edit to all accessions with this species?',
    EDIT_SPECIES_MODAL_ANSWER_NO: 'No, Only Apply Here',
    EDIT_SPECIES_MODAL_ANSWER_YES: 'Yes, Apply To All',
    ACTIVE_INACTIVE: 'Active/Inactive',
    STAGE: 'Stage',
    TEMPLATES: 'Templates',
    PROCESSED_AND_DRIED_BY: 'Processed & Dried By',
    STORED_BY: 'Stored By',
    WITHDRAWN_BY: 'Withdrawn By',
    GERMINATION_TESTED_BY: 'Germination Tested By',
    WILD_OUTPLANT: 'Wild/Outplant',
    WILD: 'Wild',
    OUTPLANT: 'Outplant',
    GRAMS: 'Grams',
    KILOGRAMS: 'Kilograms',
    MILLIGRAMS: 'Milligrams',
    OUNCES: 'Ounces',
    POUNDS: 'Pounds',
    UNITS: 'Units',
    REQUIRED_FIELD: 'Required field.',
    SCHEDULED_FOR_TESTING: 'Scheduled for Testing',
    SCHEDULED_SEEDS: '{0} Seeds',
    SEND_TO_NURSERY: 'Send to Nursery',
    SENDING: 'Sending...',
    SENT_TO_NURSERY: 'Sent to Nursery!',
    UNDO_SEND_TO_NURSERY: 'Undo Send to Nursery',
    GO_TO_DATABASE: 'Go to Database',
    AUTOCALCULATED: '(Auto-calculated)',
    EDIT_NUMBER_OF_GERMINATED_SEEDS: 'Edit Number of Germinated Seeds',
    S_SEED_COUNT: 'seed count',
    G_GRAMS: 'g (grams)',
    MG_MILLIGRAMS: 'mg (milligrams)',
    KG_KILOGRAMS: 'kg (kilograms)',
    LB_POUNDS: 'lb (pounds)',
    OZ_OUNCES: 'oz (ounces)',
    GOT_IT: 'Got It!',
    VIEW_COLLECTIONS: 'View collections',
    BAGS_TOTAL: 'Bags Total',
    CHECKIN_BAGS: 'Check In Bags',
    VIEW_ACCESSION: 'View accession',
    CHECKING_IN: 'Checking In...',
    CHECK_IN: 'Check In',
    CHECKED_IN: 'Checked In!',
    CHECK_IN_BAGS: 'Check In Bags',
    SITES: 'Sites',
    PEOPLE: 'People',
    CHECK_IN_MESSAGE:
      '{0} new seed collection bags should have been dropped off at the seed bank. Please verify their arrival and check them in.',
    SPECIES_DESCRIPTION: 'Manage your organization’s species list for planning, operation and reporting.',
    ADD_SITE: 'Add Site',
    NAME: 'Name',
    NAME_REQUIRED: 'Name *',
    DESCRIPTION_REQUIRED: 'Description *',
    DESCRIPTION: 'Description',
    ADMIN: 'Admin',
    ADD_PERSON: 'Add Person',
    EDIT_PERSON: 'Edit Person',
    PEOPLE_DESCRIPTION: 'Manage the people in Terraware.',
    CREATE_NEW_ORGANIZATION: 'Create New Organization',
    ADD_NEW_ORGANIZATION: 'Add New Organization',
    NATIVE_FOREST_RESTORATION: 'Native Forest Restoration',
    AGROFORESTRY: 'Agroforestry',
    SILVOPASTURE: 'Silvopasture',
    SUSTAINABLE_TIMBER: 'Sustainable Timber',
    NO_PEOPLE_IN_ORG: 'No People in Organization',
    ADD_PEOPLE_MESSAGE: 'To add people to this organization go to People.',
    REMOVE: 'Remove',
    REMOVED_PEOPLE_WARNING_DESC: 'The people you’ve removed include',
    REMOVE_AND_SAVE: 'Remove & Save',
    MOVE: 'Move',
    ADD_PERSON_DESC: 'Enter the person’s information below',
    EMAIL: 'Email',
    EMAIL_REQUIRED: 'Email *',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    ROLES_INFO: 'Select a role for this person.',
    CONTRIBUTOR_INFO: 'A contributor can only input and edit data entries for seeds and plants.',
    ADMIN_INFO: 'An admin can edit the organization profile, manage users in the organization and manage species.',
    ROLE: 'Role',
    ALREADY_INVITED_PERSON_ERROR:
      'It looks like you have already added or invited this person. Please enter a unique email address or go to the existing person’s profile.',
    GO_TO_PROFILE: 'Go to Profile',
    DATE_ADDED: 'Date Added',
    ORGANIZATION_NAME: 'Organization Name',
    ORGANIZATION_NAME_REQUIRED: 'Organization Name *',
    COUNTRY: 'Country',
    STATE: 'State',
    EDIT_ORGANIZATION: 'Edit Organization',
    ORGANIZATION: 'Organization',
    ORGANIZATION_DESC: 'Manage your organization.',
    NUMBER_OF_PROJECTS: 'Number of Projects',
    NUMBER_OF_PEOPLE: 'Number of People',
    ORGANIZATION_CREATE_FAILED: 'Unable to create organization.',
    ORGANIZATION_CREATED_TITLE: 'You have created {0}!',
    ORGANIZATION_CREATED_MSG:
      'You can access the organizations you’re in by clicking the arrow in the top right corner next to your profile.',
    GO_TO_SEED_BANKS: 'Go to Seed Banks',
    COMMON_NAME: 'Common Name',
    SCIENTIFIC_NAME_REQUIRED: 'Scientific Name *',
    SCIENTIFIC_NAME: 'Scientific Name',
    DOWNLOAD_AS_REPORT: 'Download as Report',
    ORGANIZATION_DATA_NOT_AVAILABLE: 'Organization Data Not Available',
    SPECIES_DATA_NOT_AVAILABLE: 'Species Data Not Available',
    CONTACT_US_TO_RESOLVE_ISSUE: 'Please contact us to resolve this issue.',
    EMAIL_ALREADY_EXISTS: 'This email already exists.',
    NO_MOBILE_SUPPORT_TITLE: 'Terraware web doesn’t support mobile yet.',
    NO_MOBILE_SUPPORT_DESC: 'Please access terraware.io on a desktop device.',
    MY_ACCOUNT: 'My Account',
    MY_ACCOUNT_DESC: 'Manage your account information.',
    UNABLE_TO_ADD_PERSON: 'Unable to Add Person',
    FIX_HIGHLIGHTED_FIELDS: 'Fix the highlighted fields below.',
    DETAILS: 'Details',
    NO_NOTIFICATIONS: 'No notifications to show.',
    UNEXPECTED_ERROR: 'An unexpected error occurred.',
    REMOVE_ONLY_ONE_ORG_AT_A_TIME: 'You may only remove yourself from one organization at a time.',
    REMOVING_ORG_WARNING:
      'Removing yourself from {0} means you won’t have access to this organization’s data anymore. Are you sure you want to save your changes?',
    LEAVE_AND_SAVE: 'Leave and Save',
    ASSIGN_NEW_OWNER_DESC: 'In order to remove the current owner, you must assign a new owner.',
    ASSIGN: 'Assign',
    CANNOT_REMOVE_MSG:
      'You cannot remove yourself because there is no one else in the organization. Would you like to delete the organization instead?',
    DELETE_ORGANIZATION_MSG: 'Are you sure you want to delete {0}?',
    ADD_A_SPECIES: 'Add a Species',
    CONSERVATION_STATUS: 'Conservation Status',
    SEED_STORAGE_BEHAVIOR: 'Seed Storage Behavior',
    TYPE_TO_SEARCH: 'Type to search...',
    TYPE: 'Type...',
    SELECT: 'Select...',
    SCIENTIFIC_NAME_NOT_FOUND: '“{0}” was not found in our database, but you can still add it.',
    FILL_OUT_ALL_FIELDS: 'Please fill out all required fields.',
    DUPLICATE_SPECIES_FOUND: 'Duplicate species found.',
    CANNOT_REMOVE_DELETE_MSG:
      'You cannot remove yourself because there is no one else in the organization. Would you like to delete the organization instead?',
    GROWTH_FORM: 'Growth Form',
    CONSERV_STATUS: 'Conserv. Status',
    EDIT: 'Edit',
    SEARCH_BY_NAME_OR_FAMILY: 'Search by name or family...',
    SETTINGS: 'Settings',
    MARK_ALL_AS_READ: 'Mark All As Read',
    SOMETHING_WENT_WRONG: 'Something went wrong.',
    UNABLE_TO_LOAD_NOTIFICATIONS: 'Unable to load notifications. Try again later.',
    NOTIFICATIONS: 'Notifications',
    MARK_AS_READ: 'Mark As Read',
    MARK_AS_UNREAD: 'Mark As Unread',
    TAKE_ME_THERE: 'Take Me There',
    MY_ACCOUNT_NOTIFICATIONS_DESC:
      'Notifications alert you when there are important updates about your organizations. You will receive them through email.',
    RECEIVE_EMAIL_NOTIFICATIONS: 'Receive Email Notifications',
    IMPORT_DATA: 'Import Data',
    FILE_SELECTED: 'File Selected',
    IMPORT_SPECIES_LIST: 'Import Species List',
    IMPORT_SPECIES_LIST_DESC: 'Browse or drag and drop a CSV with scientific names and other optional fields.',
    DOWNLOAD_CSV_TEMPLATE: 'Download a CSV template here.',
    CHOOSE_FILE: 'Choose File...',
    REPLACE_FILE: 'Replace File...',
    DATA_IMPORT_FAILED: 'Data import failed',
    TRY_AGAIN: 'Try Again',
    CANCEL_IMPORT: 'Cancel Import',
    IMPORTING_SPECIES: 'Importing species...this may take a few minutes.',
    SPECIES_IMPORT_COMPLETE: 'Species data import complete!',
    NICE: 'Nice!',
    DUPLICATED_SPECIES: 'We found {0} duplicated species:',
    REPLACE: 'Replace',
    KEEP_ORIGINAL: 'Keep Original',
    SEED_BANKS: 'Seed Banks',
    ADD_A_SEED_BANK: 'Add a Seed Bank',
    SEED_BANK_SETUP: 'Seed Bank Setup',
    ADD_SEED_BANK: 'Add Seed Bank',
    MONITORING: 'Monitoring',
    SEED_BANK_ADDED: 'Seed Bank added.',
    SENSOR_KIT: 'Sensor Kit',
    SENSOR_KIT_HAS_BEEN_SET_UP: 'Sensor Kit has been set up. Go to the {0} page to see them.',
    SENSOR_KIT_READY_TO_SET_UP:
      'If you have a Terraformation seed bank, its sensor kit is ready to be set up. Take me to the {0} page to set it up.',
    SELECT_SEED_BANK: 'Select Seed Bank',
    SELECT_SEED_BANK_INFO: 'Accessions require a seed bank storage location. Please select a seed bank.',
    SELECT_BUTTON: 'Select',
    SEED_BANK: 'Seed Bank',
    SET_UP_YOUR_SENSOR_KIT: 'Set Up Your Sensor Kit',
    SET_UP_YOUR_SENSOR_KIT_MSG:
      "If your seed bank was built by Terraformation, it is equipped with a sensor kit that you can remotely monitor things like the seed bank's temperature and humidity. To set this up, you'll need to connect your seed bank to the Terraware web app. This may take up to 30 minutes.",
    START_SET_UP: 'Start Setup',
    NEXT: 'Next',
    SENSOR_KIT_SET_UP: 'Sensor Kit Set Up',
    TEMPERATURE_AND_HUMIDITY_SENSOR_DATA: 'Temperature & Humidity Sensor Data',
    TIME_PERIOD: 'Time Period',
    REFRESH_DATA: 'Refresh Data',
    SENSOR_KIT_SET_UP_TITLE: "Let's Set Up Your Sensor Kit!",
    SENSOR_KIT_SET_UP_DESCRIPTION: "If your seed bank has a sensor kit, let's set it up below.",
    SENSOR_KIT_SET_UP_TIME: 'This may take up to 30 minutes.',
    SENSOR_KIT_SET_UP_PV_SYSTEM: 'Select PV System',
    SENSOR_KIT_SET_UP_PV_SYSTEM_DESCRIPTION:
      'Our seed banks support multiple types of PV systems; select which one you have so that we can accurately display battery charge.',
    SENSOR_KIT_SET_UP_SENSOR_KIT_ID: 'Enter Sensor Kit ID',
    SENSOR_KIT_SET_UP_SENSOR_KIT_ID_DESCRIPTION:
      'Find your sensor kit ID on the outside of your sensor kit. This will connect the Device Manager inside the kit to our database.',
    SENSOR_KIT_SET_UP_DEVICE_MANAGER: 'Install Device Manager Update',
    SENSOR_KIT_SET_UP_DEVICE_MANAGER_DESCRIPTION:
      'To detect your sensors, the device manager in your sensor kit needs to download the latest code; this may take up to 20 minutes. The download starts the moment your sensor kit is connected to the internet, so this step might alread be complete.',
    SENSOR_KIT_SET_UP_DETECT_SENSORS: 'Detect Sensors',
    SENSOR_KIT_SET_UP_DETECT_SENSORS_DESCRIPTION:
      "To power on sensors, remove the paper tabs blocking the batteries. When sensors are powered on and within range, they'll be detected by the device manager automatically.",
    SENSOR_KIT_SET_UP_SENSOR_LOCATIONS: 'Assign Sensor Locations',
    SENSOR_KIT_SET_UP_SENSOR_LOCATIONS_DESCRIPTION:
      'Your sensor kit includes 14 temperature/humidity sensors. Please put one sensor in each location. Select which sensor you put in each location using the dropdown.',
    SENSOR_KIT_SET_UP_COMPLETE: 'Setup Complete!',
    SENSOR_KIT_SET_UP_COMPLETE_DESCRIPTION:
      'You will now be able to view solar battery charge and sensor data in your sensor monitoring dashboard.',
    PV_SYSTEM: 'PV system',
    PV_BATTERY_CHARGE: 'PV Battery Charge',
    SEED_BANK_INTERNET: 'Seed Bank Internet',
    CONNECTED: 'Connected',
    NOT_CONNECTED: 'Not Connected',
    ENTER_SIX_DIGIT_KEY: 'Enter 6-digit key',
    SENSOR_KIT_ID_PLACEHOLDER: 'XXXXXX',
    KEY_WAS_NOT_RECOGNIZED: 'Key was not recognized.',
    PLEASE_TRY_AGAIN: 'Please try again.',
    SERVER_ERROR: 'Server Error',
    KEY_BELONGS_TO_ANOTHER_SEED_BANK: 'Key is associated with another seed bank.',
    PV_BATTERY: 'PV Battery',
    DOWNLOAD_IN_PROGRESS: 'Download in progress...',
    CONNECT_FAILED: 'Connect failed',
    UNABLE_TO_CONNECT_TO_SENSOR_KIT:
      'We were unable to connect to your sensor kit. Sometimes this is because it is not connected to power or internet. Please email {0} so we can assist you.',
    DOWNLOAD_COMPLETE: 'Download complete',
    DOWNLOAD_FAILED: 'Download failed',
    DOWNLOAD_FAILED_DESCRIPTION: 'The download has failed. Please email {0} so we can assist you.',
    WAITING_TO_DOWNLOAD: 'Waiting to download...',
    SENSORS_FOUND: '{0}/{1} sensors found...',
    ALL_SENSORS_FOUND: 'All sensors found.',
    SENSOR_SCAN_TIMEOUT: 'Sensor Scan Timeout',
    SENSOR_SCAN_TIMEOUT_ERROR:
      "Only {0}/{1} sensors were found. Please make sure all sensors are powered on and within range, then try again. If this problem persists, you might have broken sensors; if you think that's the case, email us at {2}.",
    FRIDGE: 'Fridge',
    FREEZER: 'Freezer',
    DRY_CABINET: 'Dry Cabinet',
    DRYING_RACKS: 'Drying Racks',
    FRONT_OF_SEED_BANK: 'Front of Seed Bank',
    MIDDLE_OF_SEED_BANK: 'Middle of Seed Bank',
    BACK_OF_SEED_BANK: 'Back of Seed Bank',
    FINISH: 'Finish',
    SENSOR_LOCATION_ERROR: 'Each location much have one sensor assigned to it.',
    NO_DATA_YET: 'No data yet',
    CANCEL_DATA_CHECK: 'Cancel Data Check',
    RUN_A_DATABASE_CHECK: 'Run a Database Check',
    CHECK_DATA: 'Check Data',
    CHECKING_DATA: 'Running database check. Please wait, this may take a few minutes...',
    CHECK_DATA_DESCRIPTION:
      'You can run a database check to compare your species information with what’s stored in the GBIF Database. This will flag entries if the scientific name of your species is spelled wrong, or is missing from the database. This could take a few minutes, and you can’t cancel it once it starts.',
    DATA_CHECK_COMPLETED: 'Database check complete. No errors were found!',
    DATA_CHECK_WITH_PROBLEMS: 'Database check complete. {0} potential errors were found.',
    REVIEW_ERRORS: 'Review Errors',
    PROBLEMS: 'Problems',
    ISSUE: 'Issue',
    SUGGESTION: 'Suggestion',
    IGNORE: 'Ignore',
    ACCEPT: 'Accept',
    CHANGE_TO: 'Change to {0}',
    UNSPECIFIED: 'Unspecified',
  },
});

export default strings;
