import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
  en: {
    CANCEL: 'Cancel',
    SAVE: 'Save',
    SAVE_CHANGES: 'Save Changes',
    GENERIC_ERROR: 'An error ocurred',
    PREEXISTING_SPECIES: 'This species already exists',
    DELETE: 'Delete',
    SPECIES_NAME: 'Species Name',
    DASHBOARD: 'Dashboard',
    DELETE_SPECIES: 'Delete Species',
    DELETE_CONFIRMATION_MODAL_MAIN_TEXT:
      'Are you sure you want to delete this species? This action cannot be undone. Any plants with this species will now be categorized as “Other” for its species.',
    DELETE_PLANT: 'Delete Plant',
    DELETE_PLANT_CONFIRMATION_MODAL_MAIN_TEXT:
      'Are you sure you want to delete this plant? This action cannot be undone.',
    SNACKBAR_MSG_NEW_SPECIES_ADDED: 'New species added just now.',
    SNACKBAR_MSG_CHANGES_SAVED: 'Changes saved just now.',
    SNACKBAR_MSG_SPECIES_DELETED: 'Species deleted just now.',
    SNACKBAR_MSG_PLANT_DELETED: 'Plant deleted just now.',
    EDIT_SPECIES: 'Edit Species',
    ADD_SPECIES: 'Add Species',
    ADD: 'Add',
    NEW_SPECIES: 'New Species',
    N_OF_PLANTS: '# of Plants',
    SPECIES: 'Species',
    PLANTS: 'Plants',
    PLANTS_LIST: 'Plants List',
    NUMBER_OF_PLANTS: 'Number of Plants',
    AS_OF: 'As of',
    OTHER: 'Other',
    LOGOUT: 'Logout',
    DATE: 'Date',
    GEOLOCATION: 'Geolocation',
    PHOTO: 'Photo',
    NOTES: 'Notes',
    EXISTING_SPECIES_MSG: 'Choose Existing Species',
    CREATE_NEW_SPECIES: 'Create New Species',
    TOTAL: 'Total',
    FILTERS: 'Filters',
    FROM: 'From',
    TO: 'To',
    APPLY_FILTERS: 'Apply Filters',
    CLEAR_FILTERS: 'Clear Filters',
    GROWTH_SINCE_LAST_WEEK: '{0}% since last week',
    LOADING: 'Loading...',
    PROJECTS: 'Projects',
    PROJECT: 'Project',
    SEEDS: 'Seeds',
    ACCESSIONS: 'Accessions',
    OR: 'OR',
    FLORA: 'Flora',
    SEED_COLLECTION: 'Seed Collection',
    PROCESSING_AND_DRYING: 'Processing & Drying',
    STORAGE: 'Storage',
    WITHDRAWAL: 'Withdrawal',
    CREATE: 'Create',
    SAVING: 'Saving...',
    CREATE_ACCESSION: 'Create Accession',
    CHANGES_SAVED: 'Changes Saved!',
    GERMINATION_TESTING: 'Germination Testing',
    NURSERY: 'Nursery',
    LAB: 'Lab',
    SAVE_ACCESSION_ERROR: 'An error occurred when saving the accession.',
    GET_ACCESSION_ERROR: 'An error occurred when getting the accession.',
    START: 'Start',
    END: 'End',
    SEARCH: 'Search',
    YES: 'Yes',
    NO: 'No',
    ACCESSION: 'Accession',
    STATUS: 'Status',
    RECEIVED_DATE: 'Received Date',
    COLLECTED_DATE: 'Collected Date',
    SITE_LOCATION: 'Site Location',
    ENDANGERED: 'Endangered',
    RARE: 'Rare',
    NUMBER_OF_TREES: 'Number of Trees',
    ESTIMATED_SEEDS_INCOMING: 'Estimated Seeds Incoming',
    LANDOWNER: 'Landowner',
    PROCESSING_START_DATE: 'Processing Start Date',
    SEEDS_TOTAL: 'Quantity of Seeds',
    SEEDS_UNITS: 'Units Quantity of Seeds',
    DRYING_START_DATE: 'Drying Start Date',
    PROCESSING_METHOD: 'Processing Method',
    DRYING_END_DATE: 'Estimated Drying End Date',
    SEEDS_REMAINING: 'Seeds Remaining',
    REMAINING_UNITS: 'Remaining Units',
    STORING_START_DATE: 'Storing Start Date',
    STORAGE_CONDITION: 'Storage Condition',
    STORAGE_LOCATION: 'Storage Location',
    NUMBER_OF_STORAGE_PACKETS: 'Number of Storage Packets',
    DATE_OF_WITHDRAWAL: 'Date of Withdrawal',
    NUMBER_OF_SEEDS_WITHDRAWN: 'Seeds Withdrawn',
    DESTINATION: 'Destination',
    NUMBER_OF_SEEDS_REMAINING: 'Seeds Remaining',
    PURPOSE: 'Purpose',
    TARGET_RH: 'Target %RH',
    GERMINATION_TEST_TYPE: 'Germination Test Type',
    GERMINATION_TREATMENT: 'Germination Treatment',
    SEED_TYPE: 'Seed Type',
    NUMBER_OF_SEEDS_FILLED: 'Number of Seeds Filled',
    GERMINATION_START_DATE: 'Germination Start Date',
    NUMBER_OF_SEEDS_SOWN: 'Number of Seeds Sown',
    TOTAL_OF_SEEDS_GERMINATED: 'Total of Seeds Germinated',
    NUMBER_OF_SEEDS_EMPTY: 'Number of Seeds Empty',
    MOST_RECENT_GERMINATION_TEST_DATE: 'Most Recent Germination Test Date',
    PERCENTAGE_VIABILITY: '% Viability',
    GEMRINATION_SUBSTRATE: 'Germination Substrate',
    NUMBER_OF_SEEDS_COMPROMISED: 'Number of Seeds Compromised',
    MOST_RECENT_PERCENTAGE_VIABILITY: 'Most Recent % Viability',
    TOTAL_ESTIMATED_PERCENTAGE_VIABILITY: 'Total Estimated % Viability',
    BAG_IDS: 'Bag IDs',
    REPORT: 'Report',
    DOWNLOAD_REPORT_DESCRIPTION:
      'You are about to download this datatable as a report. This csv file can be found in your Downloads. Please name your report below.',
    BOTH_WITHDRAWS_DESCRIPTION:
      'You have withdrawn seeds by both count and weight. As a result, the app has calculated the amount of seeds withdrawn for you by weight.',
    REPORT_NAME: 'Report Name',
    DOWNLOAD: 'Download',
    ADD_COLUMNS: 'Add columns',
    ADD_COLUMNS_DESCRIPTION: 'Select columns you want to add. Deselect columns you want to remove.',
    CLEAR: 'Clear',
    NEW_ENTRY: 'New Entry',
    SEE_ENTRIES: 'See Entries',
    TOTAL_SEEDS_GERMINATED: 'Total Seeds Germinated',
    TOTAL_ESTIMATED_VIABILITY: 'Total Estimated Viability',
    LAB_DESCRIPTION: 'All the details about lab germination tests conducted on the seeds.',
    NEW_TEST: 'New Test',
    CUT_TEST: 'Cut Test',
    FILLED_SEEDS: 'Filled Seeds',
    EMPTY_SEEDS: 'Empty Seeds',
    COMPROMISED_SEEDS: 'Compromised Seeds',
    SEEDS_GERMINATED: 'Seeds Germinated',
    SEEDS_GERMINATED_LC: 'seeds germinated',
    RECORDING_DATE: 'Recording Date',
    CREATE_ENTRY: 'Create Entry',
    SCHEDULE_DATE_INFO: 'Schedule a date by selecting a future date.',
    START_DATE: 'Start Date',
    END_DATE: 'End Date',
    FRESH_SEEDS: 'Fresh Seeds',
    STORED_SEEDS: 'Stored Seeds',
    NURSERY_MEDIA: 'Nursery Media',
    AGAR_PETRI_DISH: 'Agar Petri Dish',
    PAPER_PETRI_DISH: 'Paper Petri Dish',
    SOAK: 'Soak',
    SCARIFY: 'Scarify',
    GA3: 'GA3',
    STRATIFICATION: 'Stratification',
    SEEDS_SOWN: 'Seeds Sown',
    STAFF_RESPONSIBLE: 'Staff Responsible',
    CREATE_TEST: 'Create Test',
    SUBSTRATE: 'Substrate',
    TREATMENT: 'Treatment',
    SOWN: 'Sown',
    REMAINING: 'Remaining',
    STAFF: 'Staff',
    GERMINATED: 'Germinated',
    COLLECTED_ON: 'Collected On',
    RECEIVED_ON: 'Received On',
    NO_FUTURE_DATES: 'No future dates allowed',
    NO_NEGATIVE_NUMBERS: 'No negative numbers allowed',
    SEED_COLLECTION_DESCRIPTION: 'All the details about the species, date collected, collectors and the site location.',
    FAMILY: 'Family',
    FOUNDER_ID: 'Founder ID',
    FIELD_NOTES: 'Field Notes',
    FIELD_NOTES_PLACEHOLDER: 'Important notes about seeds, fruits, or plants',
    PRIMARY_COLLECTOR: 'Primary Collector',
    SITE: 'Site',
    FACILITY: 'Facility',
    ENVIRONMENTAL_NOTES: 'Environmental Notes',
    ENVIRONMENTAL_NOTES_PLACEHOLDER: 'Important notes about landscape, climate, and environmental conditions',
    NEW_ACCESSION: 'New Accession',
    NEW_ACCESSION_DESCRIPTION: 'An accession number will be generated once you create the accession.',
    NEW_ACCESSION_INFO:
      'Information like Seed Bags, Photos and Geolocations can only be added via the Seed Collector Android app. All the other information about processing, drying, storage and withdrawals can be added after first creating the accession.',
    SEED_BAGS: 'Seed Bags',
    PHOTOS: 'Photos',
    GEOLOCATIONS: 'Geolocations',
    NEXT_PROCESSING_AND_DRYING: 'Next: Processing & Drying',
    UNSURE: 'Unsure',
    ACCESSION_SAVED: 'Accession saved',
    ADD_NEW: 'Add New',
    NURSERY_DESCRIPTION: 'All the details about nursery germination tests conducted on the seeds.',
    PROCESSING_AND_DRYING_DESCRIPTION: 'All the details about processing and drying the seeds.',
    QUANTIFY: 'Quantify',
    SEED_WEIGHT: 'Seed Weight',
    SEED_COUNT: 'Seed Count',
    SUBSET_WEIGHT: 'Subset’s Weight of Seeds',
    NUMBER_OF_SEEDS_IN_SUBSET: '# of Seeds in Subset',
    TOTAL_WEIGHT_OF_SEEDS: 'Total Weight of Seeds',
    TOTAL_SEEDS_COUNT_ESTIMATION: 'Total Seeds Count Estimation',
    VIABILITY_TEST_TYPES: 'Viability Test Types',
    VIABILITY_TEST_TYPE: 'Viability Test Type',
    VIABILITY_TEST_TYPES_INFO:
      'Selecting either one will unlock a new option on the sidebar after you save the changes.',
    NURSERY_GERMINATION: 'Nursery Germination',
    LAB_GERMINATION: 'Lab Germination',
    ESTIMATED_DRYING_END_DATE: 'Estimated Drying End Date',
    SCHEDULE_DATE_TO_MOVE: 'Schedule Date to Move from Racks to Dry Cabinets',
    IF_APPLIES: 'Only if it applies',
    PROCESSING_AND_DRYING_INFO:
      'By adding information about processing/drying and saving changes, you will be automatically changing this accession’s stage from Pending to either Processing, Processed, Drying, or Dried, depending on the information you fill in.',
    NEXT_STORING: 'Next: Storing',
    STORAGE_DESCRIPTION: 'All the details about storing the seeds.',
    STARTING_ON: 'Starting On',
    NUMBER_OF_PACKETS: 'Number of Packets',
    STORAGE_INFO:
      'By adding information about storage and saving changes, you will be automatically changing this accession’s stage from Pending to Stored.',
    NEXT_WITHDRAWAL: 'Next: Withdrawal',
    LOCATION: 'Location',
    CONDITION: 'Condition',
    SUMMARY: 'Summary',
    WELCOME_MSG: 'Welcome and happy seeding!',
    ACTIVE_ACCESSIONS: 'Active Accessions',
    MOST_RECENT_STAGE_UPDATES: 'Most Recent Stage Updates',
    PENDING_UPDATES:
      'There are {0} seed collection bags have been waiting since drop off for at least 1 week and are ready to be processed.',
    PROCESSED_UPDATES:
      '{0} accessions have finished processing for at least 2 weeks and are ready to be tested for %RH (or dried).',
    DRIED_UPDATES: '{0} accessions have past its drying end date and are ready to be stored.',
    WITHDRAWN_UPDATES: '{0} accessions have been completely withdrawn this week and are now inactive.',
    WITHDRAWAL_DESCRIPTION: 'All the details about withdrawal of the seeds.',
    ALL_SEEDS_WITHDRAWN_MSG:
      "As all seeds have been withdrawn, new withdrawals are disabled, the accession's stage has been set to Withdrawn, and the accession itself marked as Inactive",
    INITIAL_SEEDS: 'Initial Seeds',
    SEEDS_WITHDRAWN: 'Seeds Withdrawn',
    SEEDS_WITHDRAWN_UNITS: 'Seeds Withdrawn Units',
    WITHDRAW_REMAINING_SEEDS: 'Withdraw All Remaining Seeds',
    ZERO: 'zero',
    AVAILABLE: 'available',
    NEW_WITHDRAWAL: 'New Withdrawal',
    WITHDRAWN: 'Withdrawn',
    SCHEDULE_WITHDRAWAL: 'Schedule Withdrawal',
    SCHEDULED: '(Scheduled)',
    SCHEDULING_FOR: 'Scheduling for: {0}',
    WITHDRAW_SEEDS: 'Withdraw seeds',
    WITHDRAWN_ON: 'Withdrawn On',
    PROPAGATION: 'Propagation',
    OUTREACH_OR_EDUCATION: 'Outreach or Education',
    RESEARCH: 'Research',
    BROADCAST: 'Broadcast',
    SHARE_WITH_ANOTHER_SITE: 'Share with another Site',
    SCHEDULED_FOR: 'Scheduled for',
    ALERTS: 'Alerts',
    EDIT_SPECIES_MODAL_QUESTION: 'Would you like to apply this edit to all accessions with this species?',
    EDIT_SPECIES_MODAL_ANSWER_NO: 'No, Only Apply Here',
    EDIT_SPECIES_MODAL_ANSWER_YES: 'Yes, Apply To All',
    ACTIVE_INACTIVE: 'Active/Inactive',
    STAGE: 'Stage',
    TEMPLATES: 'Templates',
    PROCESSED_AND_DRIED_BY: 'Processed & Dried By',
    STORED_BY: 'Stored By',
    WITHDRAWN_BY: 'Withdrawn By',
    GERMINATION_TESTED_BY: 'Germination Tested By',
    TOUR_TITLE: 'Hey! Want a tour?',
    TOUR_DESCRIPTION: 'There are many things you can do in Seed Bank App. Take the tour to find out what.',
    ACCEPT_TOUR: 'Hell Yeah!',
    DECLINE_TOUR: 'Maybe Later',
    ONBOARDING_TITLE_STEP_1: 'Meet the Summary Page',
    ONBOARDING_DESCRIPTION_STEP_1:
      'Get an overview of all your data. This page includes statistics, such as active accessions, species, and families, alerts from the Seed Bank Dashboard, and updates regarding what stage your accessions are in.',
    ONBOARDING_TITLE_STEP_2: 'All Your Accessions in One Place',
    ONBOARDING_DESCRIPTION_STEP_2:
      'Go to this page to view and easily manage all of your accessions. You can add or data any data as you complete each task in the seed bank.',
    ONBOARDING_TITLE_STEP_3: 'Help/FAQs',
    ONBOARDING_DESCRIPTION_STEP_3:
      'Confused? Click on this icon to see more information on how to use this app to its fullest extent.',
    ONBOARDING_TITLE_STEP_4: 'Find Your Notifications Here',
    ONBOARDING_DESCRIPTION_STEP_4:
      'Get all the latest reminders about your accessions. Never miss out on any important information.',
    ONBOARDING_TITLE_STEP_5: 'Manually Add Accessions If Needed',
    ONBOARDING_DESCRIPTION_STEP_5: 'Received a new bag of seeds? Click this button to add it to the database.',
    ONBOARDING_NEXT_STEP: 'Got It!',
    SKIP_ONBOARDING: 'Skip Tour',
    ONBOARDING_LAST_STEP: 'All Done!',
    WILD_OUTPLANT: 'Wild/Outplant',
    WILD: 'Wild',
    OUTPLANT: 'Outplant',
    GRAMS: 'Grams',
    KILOGRAMS: 'Kilograms',
    MILLIGRAMS: 'Milligrams',
    OUNCES: 'Ounces',
    POUNDS: 'Pounds',
    UNITS: 'Units',
    REQUIRED_FIELD: '* Required Field',
    SCHEDULED_FOR_TESTING: 'Scheduled for Testing',
    SCHEDULED_SEEDS: '{0} Seeds',
    SEND_TO_NURSERY: 'Send to Nursery',
    SENDING: 'Sending...',
    SENT_TO_NURSERY: 'Sent to Nursery!',
    UNDO_SEND_TO_NURSERY: 'Undo Send to Nursery',
    GO_TO_DATABASE: 'Go to Database',
    AUTOCALCULATED: '(Auto-calculated)',
    EDIT_NUMBER_OF_GERMINATED_SEEDS: 'Edit Number of Germinated Seeds',

    HELP_HEADER_TITLE: 'Seed Bank FAQs',
    HELP_HEADER_QUICK_TOUR: 'Quick Tour',
    HELP_HEADER_QUICK_TOUR_TEXT:
      'Take a tour to find out the many things you can do on the Seed Bank App! We’ll walk you through the main pages and functionalities.',
    HELP_HEADER_QUICK_TOUR_BUTTON: 'Let’s Do It!',
    S_SEED_COUNT: 'seed count',
    G_GRAMS: 'g (grams)',
    MG_MILLIGRAMS: 'mg (milligrams)',
    KG_KILOGRAMS: 'kg (kilograms)',
    LB_POUNDS: 'lb (pounds)',
    OZ_OUNCES: 'oz (ounces)',
    GOT_IT: 'Got It!',
    VIEW_COLLECTIONS: 'View collections',
    BAGS_TOTAL: 'Bags Total',
    CHECKIN_BAGS: 'Check In Bags',
    VIEW_ACCESSION: 'View accession',
    CHECKING_IN: 'Checking In...',
    CHECK_IN: 'Check In',
    CHECKED_IN: 'Checked In!',
    CHECK_IN_BAGS: 'Check In Bags',
    SITES: 'Sites',
    PEOPLE: 'People',
    CHECK_IN_MESSAGE:
      '{0} new seed collection bags should have been dropped off at the seed bank. Please verify their arrival and check them in.',
    SEEDS_CARD_DESCRIPTION:
      'Collect seeds and then record and view your accessions. Seed accessions can be viewed and analyzed by Facilities.',
    PLANTS_CARD_DESCRIPTION:
      'They’ve taken root! View all your plants in one place. Plants can be viewed and analyzed by Project.',
    SPECIES_CARD_DESCRIPTION: 'View the Species that are referenced by your Seed and Plant entries.',
    PROJECTS_CARD_DESCRIPTION:
      'Manage Projects to organize all your Earth saving activities and data. A reforestation Project, for example, will have Sites, which in turn will have Facilities, along with team members who will be involved with the Project.',
    SITES_CARD_DESCRIPTION: 'View Sites under your Project. A Project may have one or more Sites.',
    PEOPLE_CARD_DESCRIPTION: 'We can’t do it alone! Add people to your Organization and assign them roles.',
    GOOD_MORNING: 'Good morning!',
    GOOD_MORNING_PERSON: 'Good morning, {0}!',
    ADD_PROJECT: 'Add Project',
    PROJECTS_DESCRIPTION: 'Manage your Projects.',
    ADD_SITE: 'Add Site',
    SITES_DESCRIPTION: 'Manage your Sites.',
    NAME: 'Name',
    DESCRIPTION: 'Description',
    START_DATE_OPT: 'Start Date (optional)',
    STATUS_OPT: 'Status (opt)',
    PROJECT_TYPE_OPT: 'Project Type(s) (optional)',
    PEOPLE_DESC: 'To add new people to this organization go to People.',
    SITES_DESC: 'To add new sites to this project go to Sites.',
    ADMIN: 'Admin',
    ADD_PERSON: 'Add Person',
    PEOPLE_DESCRIPTION: 'Manage the people in Terraware.',
    CREATE_NEW_ORGANIZATION: 'Create New Organization',
    ADD_NEW_ORGANIZATION: 'Add New Organization',
    ADD_PROJECT_DESC: 'Enter the project’s information below and then select the people you would like to add.',
    NATIVE_FOREST_RESTORATION: 'Native Forest Restoration',
    AGROFORESTRY: 'Agroforestry',
    SILVOPASTURE: 'Silvopasture',
    SUSTAINABLE_TIMBER: 'Sustainable Timber',
    ADD_PEOPLE: 'Add People',
    EDIT_PROJECT: 'Edit Project',
    NO_PEOPLE_IN_ORG: 'No People in Organization',
    ADD_PEOPLE_MESSAGE: 'To add people to this organization go to People.',
    REMOVE: 'Remove',
    REMOVED_PEOPLE_WARNING: 'You’ve removed people from this project. Are you sure you want to save your changes?',
    REMOVED_SITES_WARNING: 'You’ve removed sites from this project. Are you sure you want to save your changes?',
    REMOVED_PEOPLE_AND_SITES_WARNING:
      'You’ve removed people and sites from this project. Are you sure you want to save your changes?',
    REMOVED_PEOPLE_WARNING_DESC: 'The people you’ve removed include',
    REMOVED_SITES_WARNING_DESC: 'The sites you’ve removed include',
    REMOVED_PEOPLE_AND_SITES_WARNING_DESC:
      'The people you’ve removed include {0} and the sites you’ve removed include {1}',
    REMOVE_AND_SAVE: 'Remove & Save',
    MOVE: 'Move',
    REASSIGN_SITE_TITLE: 'Please reassign this site to another project in order to remove it from this project.',
    ADD_SITE_DESC: 'Enter the site’s information below.',
    EDIT_SITE: 'Edit Site',
    ADD_PERSON_DESC: 'Enter the person’s information below and then check the Projects you would like to add them to. ',
    EMAIL: 'Email',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    ROLES_INFO: 'Select a role for this person.',
    CONTRIBUTOR_INFO: 'A contributor can only input and edit data entries for seeds and plants.',
    MANAGER_INFO: 'A manager can do the above as well as invite users to projects, edit sites, and manage species.',
    ADMIN_INFO:
      'An admin can do the above as well as edit the organization profile, manage users in the organization, manager projects, and manage sites.',
    ADD_TO_PROJECT_DESC: 'To add new projects to this organization go to Projects.',
    ROLE: 'Role',
    ADD_TO_PROJECT: 'Add to Project',
    NO_PROJECTS_IN_ORG: 'No Projects in Organization',
    ADD_PROJECTS_MESSAGE: 'To add projects to this organization go to Projects.',
    ALREADY_INVITED_PERSON_ERROR:
      'It looks like you have already added or invited this person. Please enter a unique email address or go to the existing person’s profile.',
    GO_TO_PROFILE: 'Go to Profile',
    DATE_ADDED: 'Date Added',
    PROJECTS_DESC: 'To add new projects to this organization go to Projects.',
    ORGANIZATION_NAME: 'Organization Name',
    COUNTRY_OPTIONAL: 'Country (optional)',
    STATE_OPTIONAL: 'State (optional)',
    EDIT_ORGANIZATION: 'Edit Organization',
    ORGANIZATION: 'Organization',
    ORGANIZATION_DESC: 'Manage your organization.',
    DATE_ADDED: 'Date Added',
    NUMBER_OF_PROJECTS: 'Number of Projects',
    NUMBER_OF_PEOPLE: 'Number of People',
    ORGANIZATION_CREATED_MSG:
      'You have created {0}. You can access the organizations you’re in by clicking the arrow in the top right corner next to your profile.',
  },
});

export default strings;
