export const strings = {
  ACCEPT: 'Accept',
  ACCESSION_BY_STATUS: 'Accession by Status',
  ACCESSION_CHECKED_IN: 'Accession checked in!',
  ACCESSION_DETAIL: 'Accession Detail',
  ACCESSION_DETAILS: 'Accession Details',
  ACCESSION_HISTORY: 'Accession History',
  ACCESSION_ID: 'Accession ID',
  ACCESSION_NUMBER_CHECKED_IN: 'Accession {0} was successfully checked in!',
  ACCESSION_SAVED: 'Accession saved',
  ACCESSION: 'Accession',
  ACCESSIONS_CARD_DESCRIPTION:
    'Collect seeds and then record and view your accessions. Seed accessions can be viewed and analyzed by seed bank.',
  ACCESSIONS_DATABASE_DESCRIPTION: 'Manage your accessions in Terraware.',
  ACCESSIONS_IMPORT_COMPLETE: 'Accessions data import complete!',
  ACCESSIONS_ONBOARDING_SEEDBANKS_MSG: 'Define storage locations assigned to seed accessions',
  ACCESSIONS_ONBOARDING_SPECIES_MSG: 'Define a list of species used in your seed inventory',
  ACCESSIONS_TO_BE_CHECKED_IN: 'There are {0} accessions to check in.',
  ACCESSIONS: 'Accessions',
  ACTIVE_INACTIVE: 'Active/Inactive',
  ADD_A_NURSERY: 'Add a Nursery',
  ADD_A_PLANTING_SITE_SUBTITLE:
    'Where do your plants take root? Set up your planting site so you can keep track of your plants’ progress.',
  ADD_A_PLANTING_SITE: 'Add a Planting Site',
  ADD_A_SEED_BANK: 'Add a Seed Bank',
  ADD_A_SPECIES: 'Add a Species',
  ADD_A_VIABILITY_TEST: 'Add a Viability Test',
  ADD_A_VIABILITY_TESTING: 'Add a Viability Testing',
  ADD_ADDRESS: 'Add Address',
  ADD_AN_ACCESSION: 'Add an Accession',
  ADD_BATCH: 'Add Batch',
  ADD_CONTRIBUTORS: 'Add Contributors',
  ADD_GPS_COORDINATES: 'Add GPS Coordinates',
  ADD_INVENTORY_DESCRIPTION:
    'Add inventory from a new source. To add inventory from an existing seed accession, go to Accessions and withdraw from an accession entry.',
  ADD_INVENTORY_MANUALLY_DESCRIPTION:
    'Enter species, quantities, and other relevant information using our inventory form.',
  ADD_INVENTORY: 'Add Inventory',
  ADD_MANUALLY: 'Add Manually',
  ADD_NEW: 'Add New',
  ADD_NOTES: 'Add Notes',
  ADD_NURSERIES: 'Add Nurseries',
  ADD_NURSERY_SUBTITLE:
    'How do you manage your seedlings? Set up your nursery so you can keep track of your seedlings’ growth.',
  ADD_NURSERY: 'Add Nursery',
  ADD_OBSERVATION: 'Add Observation',
  ADD_ORGANIZATION: 'Add Organization',
  ADD_PEOPLE_MESSAGE: 'To add people to this organization go to People.',
  ADD_PERSON_DESC: 'Fill out this page to add a person to the organization.',
  ADD_PERSON_GENERAL_DESC: 'Enter the person’s information below.',
  ADD_PERSON: 'Add Person',
  ADD_PHOTOS_DESCRIPTION_OPTIONAL: 'Take an optional photo (or photos) of the batches.',
  ADD_PHOTOS_DESCRIPTION:
    'Take a photo (or photos) of the batches that will be planted at the selected plot. Be sure to include the entire withdrawal in the photo(s).',
  ADD_PHOTOS_REQUIRED_OUTPLANT: 'Photos are required for Outplant withdrawals.',
  ADD_PHOTOS_REQUIRED: 'Add Photos *',
  ADD_PHOTOS: 'Add Photos',
  ADD_PLANT_SITE_DESCRIPTION: 'Add Plant and Site Description',
  ADD_PLANTING_SITE: 'Add Planting Site',
  ADD_QUANTITY: 'Add Quantity',
  ADD_SEED_BANK_SUBTITLE:
    'How do you process and store your seeds? Set up your seed bank so you can keep track of where your seeds are stored.',
  ADD_SEED_BANK: 'Add Seed Bank',
  ADD_SEED_BANKS: 'Add Seed Banks',
  ADD_SEEDLING_BATCH: 'Add Seedling Batch',
  ADD_SPECIES_MANUALLY_DESCRIPTION: 'Enter scientific name and other optional fields manually, one species at a time.',
  ADD_SPECIES: 'Add Species',
  ADD_TEST: 'Add Test',
  ADD_VIABILITY_TEST: 'Add Viability Test',
  ADD_VIABILITY: 'Add Viability',
  ADD: 'Add',
  ADMIN_INFO:
    'An admin can do the above as well as edit the organization profile, manage users in the organization, and manage seed banks.',
  ADMIN: 'Admin',
  AGAR_PETRI_DISH: 'Agar Petri Dish',
  AGAR: 'Agar',
  AGE_MONTHS: 'Age (month)',
  AGE_YEARS: 'Age (yr)',
  AGE: 'Age',
  AGROFORESTRY: 'Agroforestry',
  ALERTS: 'Alerts',
  ALL_SEEDS_WITHDRAWN_MSG:
    "As all seeds have been withdrawn, new withdrawals are disabled, the accession's stage has been set to Withdrawn, and the accession itself marked as Inactive",
  ALL_SENSORS_FOUND: 'All sensors found.',
  ALREADY_INVITED_PERSON_ERROR:
    'It looks like you have already added or invited this person. Please enter a unique email address or go to the existing person’s profile.',
  AMOUNT_REMAINING: 'Amount ({0} remaining)',
  APPLY_FILTERS: 'Apply Filters',
  APPLY_RESULT_QUESTION: 'Do you want to apply this result to the accession?',
  APPLY_RESULT: 'Apply Result',
  APPLY: 'Apply',
  ARE_YOU_SURE: 'Are you sure?',
  AS_OF: 'As of',
  ASSIGN_NEW_OWNER_DESC: 'In order to remove the current owner, you must assign a new owner.',
  ASSIGN_NEW_OWNER: 'Assign New Owner',
  ASSIGN: 'Assign',
  AUTOCALCULATED: '(Auto-calculated)',
  AVAILABLE: 'available',
  AWAITING_CHECK_IN: 'Awaiting Check-In',
  AWAITING_PROCESSING: 'Awaiting Processing',
  BACK_OF_SEED_BANK: 'Back of Seed Bank',
  BACK_TO_TERRAWARE: 'Back to Terraware',
  BACK: 'Back',
  BAG_ID: 'Bag ID',
  BAG_IDS: 'Bag IDs',
  BATCH_WITHDRAW_SUCCESS: '{0} {1} for a total of {2} {3} withdrawn.',
  BATCHES_PLURAL: 'batches',
  BATCHES_SINGULAR: 'batch',
  BOTH_WITHDRAWS_DESCRIPTION:
    'You have withdrawn seeds by both count and weight. As a result, the app has calculated the amount of seeds withdrawn for you by weight.',
  BOUNDARIES_AND_PLOTS: 'Boundaries and Plots',
  CANCEL_DATA_CHECK: 'Cancel Data Check',
  CHANGE_DEFAULT_WEIGHT_SYSTEM: 'You can change your default weight system from {0}',
  CANCEL_IMPORT: 'Cancel Import',
  CANCEL: 'Cancel',
  CANNOT_REMOVE_DELETE_MSG:
    'You cannot remove yourself because there is no one else in the organization. Would you like to delete the organization instead?',
  CANNOT_REMOVE_MSG:
    'You cannot remove yourself because there is no one else in the organization. Would you like to delete the organization instead?',
  CANNOT_REMOVE: 'Cannot Remove',
  CHANGE_GERMINATING_STATUS: 'Change Germinating Status',
  CHANGE_NOT_READY_STATUS: 'Change Not Ready Status',
  CHANGE_TO: 'Change to {0}',
  CHANGES_SAVED: 'Changes Saved!',
  CHECK_BACK_LATER: 'Please check back later.',
  CHECK_DATA_DESCRIPTION:
    'You can run a database check to compare your species information with what’s stored in the GBIF Database. This will flag entries if the scientific name of your species is spelled wrong, or is missing from the database. This could take a few minutes, and you can’t cancel it once it starts.',
  CHECK_DATA: 'Check Data',
  CHECK_DATE_REQUIRED: 'Check Date *',
  CHECK_DATE: 'Check Date',
  CHECK_IN_MESSAGE:
    '{0} new accessions should have been dropped off at the seed bank. Please verify their arrival and check them in.',
  CHECK_IN: 'Check In',
  CHECKED_IN: 'Checked In!',
  CHECKIN_ACCESSIONS: 'Check In Accessions',
  CHECKING_DATA: 'Running database check. Please wait, this may take a few minutes...',
  CHECKING_IN: 'Checking In...',
  CHEMICAL: 'Chemical',
  CHOOSE_FILE: 'Choose File...',
  CITY: 'City',
  CLEAR_FILTERS: 'Clear Filters',
  CLEAR: 'Clear',
  CLOSE: 'Close',
  COLLECTED_DATE: 'Collected Date',
  COLLECTED_FROM: 'Collected from',
  COLLECTED_ON: 'Collected On',
  COLLECTING_DATE_REQUIRED: 'Collecting Date *',
  COLLECTING_LOCATION: 'Collecting Location',
  COLLECTING_SITE: 'Collecting Site',
  COLLECTION_DATE_REQUIRED: 'Collection Date *',
  COLLECTION_DATE: 'Collection Date',
  COLLECTION_SITE: 'Collection Site',
  COLLECTION_SOURCE: 'Collection Source',
  COLLECTOR: 'Collector',
  COLLECTORS: 'Collectors',
  COMMON_NAME: 'Common Name',
  COMPLETE: 'Complete',
  COMPROMISED_SEEDS: 'Compromised Seeds',
  CONDITION: 'Condition',
  CONNECT_FAILED: 'Connect failed',
  CONNECTED: 'Connected',
  CONSERV_STATUS: 'Conserv. Status',
  CONSERVATION_STATUS: 'Conservation Status',
  CONTACT_US_TO_RESOLVE_ISSUE: 'Please contact us to resolve this issue.',
  CONTACT_US: 'Contact Us',
  CONTRIBUTOR_INFO: 'A contributor can only add data entries for seeds.',
  CONTRIBUTOR: 'Contributor',
  CONTRIBUTORS: 'Contributors',
  CONVERTED_VALUE_INFO: 'This value is auto-calculated for informational purposes.',
  COUNT: 'Count',
  COUNTRY_REQUIRED: 'Country *',
  COUNTRY: 'Country',
  CREATE_ACCESSION: 'Create Accession',
  CREATE_ENTRY: 'Create Entry',
  CREATE_NEW_ORGANIZATION: 'Create New Organization',
  CREATE_NEW_SPECIES: 'Create New Species',
  CREATE_ORGANIZATION: 'Create Organization',
  CREATE_SPECIES_LIST: 'Create Species List',
  CREATE_TEST: 'Create Test',
  CREATE: 'Create',
  CT: 'ct',
  CULTIVATED_EX_SITU_DESCRIPTION:
    'Plants that have been grown in a nursery, seed production area, or other propagation facility.',
  CULTIVATED_EX_SITU: 'Cultivated (Ex Situ)',
  CULTIVATED: 'Cultivated',
  CUSTOMIZE_TABLE_COLUMNS_DESCRIPTION: 'Select columns you want to add. Deselect columns you want to remove.',
  CUSTOMIZE_TABLE_COLUMNS: 'Customize table columns',
  CUT_TEST: 'Cut Test',
  DASHBOARD_MESSAGE_TITLE: 'Add Accessions to See Data',
  DASHBOARD_MESSAGE: 'Your seeds dashboard will automatically populate with data as you add accessions.',
  DASHBOARD: 'Dashboard',
  DATA_CHECK_COMPLETED: 'Database check complete. No errors were found!',
  DATA_CHECK_WITH_PROBLEMS: 'Database check complete. {0} potential errors were found.',
  DATA_IMPORT_FAILED: 'Data import failed',
  DATE_ADDED_REQUIRED: 'Date Added *',
  DATE_ADDED: 'Date Added',
  DATE: 'Date',
  DEAD: 'Dead',
  DEGREES_CELSIUS_VALUE: '{0}ºC',
  DELETE_ACCESSION_MESSAGE: 'You’re about to delete accession {0}.',
  DELETE_ACCESSION: 'Delete Accession',
  DELETE_CONFIRMATION_MODAL_MAIN_TEXT:
    'Are you sure you want to delete your selected species? This will delete them from your list, but you’ll keep all data attached to existing entries.',
  DELETE_ORGANIZATION_MSG: 'Are you sure you want to delete {0}?',
  DELETE_ORGANIZATION: 'Delete Organization',
  DELETE_SEEDLINGS_BATCHES_MSG: 'Are you sure you want to delete the seedlings batches?',
  DELETE_SEEDLINGS_BATCHES: 'Delete Seedlings Batches',
  DELETE_SPECIES: 'Delete Species',
  DELETE_VIABILITY_TEST_MESSAGE: 'You’re about to delete viability test {0}.',
  DELETE_VIABILITY_TEST: 'Delete Viability Test',
  DELETE: 'Delete',
  DELETED_SPECIES: '<deleted species>',
  DESCRIPTION_NOTES: 'Description/Notes',
  DESCRIPTION_ORGANIZATION: 'Your organization may include people, and species.',
  DESCRIPTION_PEOPLE: 'Invite those who contribute to the organization’s success.',
  DESCRIPTION_REPORT_PROBLEM: `If you’re having trouble using Terraware, please report any issues you’re having and we’ll make it right. Please mention this build version {0}.`,
  DESCRIPTION_REQUEST_FEATURE:
    'We’re always working to improve your Terraware experience and welcome your feedback on our products.',
  DESCRIPTION_REQUIRED: 'Description *',
  DESCRIPTION_SPECIES: 'Manage species that you collect or plant.',
  DESCRIPTION_TEST_APP: 'Be the first to try our new, field-tested mobile app and let us know what you think.',
  DESCRIPTION: 'Description',
  DESTINATION_REQUIRED: 'Destination *',
  DESTINATION: 'Destination',
  DETAILS: 'Details',
  DIRECTION_OR_DESCRIPTION: 'Direction or Description',
  DONE: 'Done',
  DOWNLOAD_AS_REPORT: 'Download as Report',
  DOWNLOAD_COMPLETE: 'Download complete',
  DOWNLOAD_CSV_TEMPLATE: 'Download a CSV template here.',
  DOWNLOAD_FAILED_DESCRIPTION: 'The download has failed. Please email {0} so we can assist you.',
  DOWNLOAD_FAILED: 'Download failed',
  DOWNLOAD_IN_PROGRESS: 'Download in progress...',
  DOWNLOAD_REPORT_DESCRIPTION:
    'You are about to download this datatable as a report. This csv file can be found in your Downloads. Please name your report below.',
  DOWNLOAD_THE_CSV_TEMPLATE: 'Download the CSV template.',
  DOWNLOAD: 'Download',
  DRY_CABINET: 'Dry Cabinet',
  DRYING_END_DATE: 'Estimated Drying End Date',
  DRYING_RACKS: 'Drying Racks',
  DRYING_START_DATE: 'Drying Start Date',
  DRYING: 'Drying',
  DUPLICATE_SPECIES_FOUND: 'Duplicate species found.',
  DUPLICATED_ACCESSION_NUMBER: 'We found {0} duplicated accession numbers:',
  DUPLICATED_INVENTORY: 'We found {0} duplicated inventory:',
  DUPLICATED_SPECIES: 'We found {0} duplicated species:',
  ECOSYSTEM_BOREAL_FOREST_TAIGA: 'Boreal forests/Taiga',
  ECOSYSTEM_DESERT_XERIC_SHRUBLAND: 'Deserts and xeric shrublands',
  ECOSYSTEM_FLOODED_GRASSLAND_SAVANNA: 'Flooded grasslands and savannas',
  ECOSYSTEM_MANGROVE: 'Mangroves',
  ECOSYSTEM_MEDITERRANEAN_FOREST: 'Mediterranean forests, woodlands and scrubs',
  ECOSYSTEM_MONTANE_GRASSLAND_SHRUBLAND: 'Montane grasslands and shrublands',
  ECOSYSTEM_TEMPERATE_BROADLEAF_MIXED_FOREST: 'Temperate broad leaf and mixed forests',
  ECOSYSTEM_TEMPERATE_CONIFEROUS_FOREST: 'Temperate coniferous forest',
  ECOSYSTEM_TEMPERATE_GRASSLAND_SAVANNA_SHRUBLAND: 'Temperate grasslands, savannas and shrublands',
  ECOSYSTEM_TROPICAL_CONIFEROUS_FOREST: 'Tropical and subtropical coniferous forests',
  ECOSYSTEM_TROPICAL_DRY_BROADLEAF_FOREST: 'Tropical and subtropical dry broad leaf forests',
  ECOSYSTEM_TROPICAL_GRASSLAND_SAVANNA_SHRUBLAND: 'Tropical and subtropical grasslands, savannas and shrublands',
  ECOSYSTEM_TROPICAL_MOIST_BROADLEAF_FOREST: 'Tropical and subtropical moist broad leaf forests',
  ECOSYSTEM_TUNDRA: 'Tundra',
  ECOSYSTEM_TYPE: 'Ecosystem Type',
  EDIT_ACCESSION_DETAIL: 'Edit Accession Detail',
  EDIT_ACCESSION: 'Edit Accession',
  EDIT_ACCOUNT: 'Edit Account',
  EDIT_LOCATION: 'Edit Location',
  EDIT_NUMBER_OF_GERMINATED_SEEDS: 'Edit Number of Germinated Seeds',
  EDIT_NURSERY: 'Edit Nursery',
  EDIT_ORGANIZATION: 'Edit Organization',
  EDIT_PERSON: 'Edit Person',
  EDIT_PLANTING_SITE: 'Edit Planting Site',
  EDIT_QUANTITY_DISABLED: 'Currently, you may only input a quantity when the status is "Drying" or “In Storage.”',
  EDIT_QUANTITY: 'Edit Quantity',
  EDIT_SEED_BANK: 'Edit Seed Bank',
  EDIT_SPECIES_MODAL_ANSWER_NO: 'No, Only Apply Here',
  EDIT_SPECIES_MODAL_ANSWER_YES: 'Yes, Apply To All',
  EDIT_SPECIES_MODAL_QUESTION: 'Would you like to apply this edit to all accessions with this species?',
  EDIT_SPECIES: 'Edit Species',
  EDIT_STATUS: 'Edit Status',
  EDIT_VIABILITY_TEST: 'Edit Viability Test',
  EDIT_VIABILITY: 'Edit Viability',
  EDIT: 'Edit',
  EMAIL_ALREADY_EXISTS: 'This email already exists.',
  EMAIL_REQUIRED: 'Email *',
  EMAIL: 'Email',
  EMPTY_SEEDS: 'Empty Seeds',
  END_DATE: 'End Date',
  END_DRYING_REMINDER_OFF: 'End-drying Reminder Off',
  END_DRYING_REMINDER: 'End-Drying Reminder',
  END: 'End',
  ENDANGERED: 'Endangered',
  ENTER_SIX_DIGIT_KEY: 'Enter 6-digit key',
  ENVIRONMENTAL_NOTES_PLACEHOLDER: 'Important notes about landscape, climate, and environmental conditions',
  ENVIRONMENTAL_NOTES: 'Environmental Notes',
  EST_READY_DATE: 'Est. Ready Date',
  ESTIMATED_DRYING_END_DATE: 'Estimated Drying End Date',
  ESTIMATED_READY_DATE: 'Estimated Ready Date',
  ESTIMATED_SEEDS_INCOMING: 'Estimated Seeds Incoming',
  EXISTING_SPECIES_MSG: '“{0}” is already in your species list. ',
  EXPORT_RECORDS: 'Export Records',
  EXPORT: 'Export',
  FACILITY: 'Facility',
  USE_ORGANIZATION_TIME_ZONE: "Use organization's time zone",
  FAMILY: 'Family',
  FERN: 'Fern',
  FIELD_NOTES_PLACEHOLDER: 'Important notes about seeds, fruits, or plants',
  FIELD_NOTES: 'Field Notes',
  FILE_SELECTED: 'File Selected',
  FILL_OUT_ALL_FIELDS: 'Please fill out all required fields.',
  FILLED_SEEDS: 'Filled Seeds',
  FILTERS: 'Filters',
  FINAL_QTY: 'Final Qty',
  FINISH: 'Finish',
  FIRST_NAME: 'First Name',
  FIX_HIGHLIGHTED_FIELDS: 'Fix the highlighted fields below.',
  FLORA: 'Flora',
  FOOTNOTE_WAIT_FOR_INVITATION_1: 'Not interested in creating your own organization or expecting an invitation?',
  FOOTNOTE_WAIT_FOR_INVITATION_2: 'Don’t worry. You’ll receive an email when your admin adds you to the organization.',
  FOR_LAB_AND_NURSERY_GERMINATION: 'For Lab and Nursery Germination',
  FOR_LAB_GERMINATION: 'For Lab Germination',
  FOR_NURSERY_GERMINATION: 'For Nursery Germination',
  FORB: 'Forb',
  FOUNDER_ID: 'Founder ID',
  FREEZER: 'Freezer',
  FRESH_SEEDS: 'Fresh Seeds',
  FRESH: 'Fresh',
  FRIDGE: 'Fridge',
  FROM_NURSERY_REQUIRED: 'From: Nursery *',
  FROM_NURSERY: 'From: Nursery',
  FROM_PLOT: 'From: Plot',
  FROM: 'From',
  FRONT_OF_SEED_BANK: 'Front of Seed Bank',
  G_GRAMS: 'g (grams)',
  G: 'g',
  GA3: 'GA3',
  GENERAL: 'General',
  GENERIC_ERROR: 'An error occurred',
  GEOLOCATIONS: 'Geolocations',
  GERMINATED: 'Germinated',
  GERMINATING_QUANTITY_REQUIRED: 'Germinating Quantity *',
  GERMINATING_QUANTITY: 'Germinating Quantity',
  GERMINATING: 'Germinating',
  GERMINATION_TESTED_BY: 'Germination Tested By',
  GET_ACCESSION_ERROR: 'An error occurred when getting the accession.',
  GET_STARTED: 'Get Started',
  GET_TOTAL_COUNT: 'Get Total Count',
  GO_TO_DASHBOARD: 'Go to Dashboard',
  GO_TO_DATABASE: 'Go to Database',
  GO_TO_NURSERIES: 'Go to Nurseries',
  GO_TO_PROFILE: 'Go to Profile',
  GO_TO_SEED_BANKS: 'Go to Seed Banks',
  GO_TO_SPECIES: 'Go to Species',
  GO_TO: 'Go to {0}',
  GOT_IT: 'Got It!',
  GPS_COORDINATES: 'GPS Coordinates',
  GRAMINOID: 'Graminoid',
  GRAMS: 'Grams',
  GROWTH_FORM: 'Growth Form',
  HISTORY: 'History',
  HOME: 'Home',
  ID: 'ID',
  IF_APPLICABLE: '(if applicable)',
  IF_APPLIES: 'Only if it applies',
  IGNORE: 'Ignore',
  IMPERIAL: 'Imperial',
  IMPERIAL_OZ_LB: 'Imperial (oz, lb)',
  IMPORT_ACCESSIONS_ALT_TITLE: 'Already have a seed accession database?',
  IMPORT_ACCESSIONS_DESC: 'Browse or drag and drop a CSV with accessions.',
  IMPORT_ACCESSIONS_WITH_TEMPLATE: 'Import accessions using our CSV template.',
  IMPORT_ACCESSIONS: 'Import Accessions',
  IMPORT_DATA: 'Import Data',
  IMPORT_INVENTORY_ALT_TITLE: 'Already have an inventory database?',
  IMPORT_INVENTORY_DESC: 'Browse or drag and drop a CSV with inventory data.',
  IMPORT_INVENTORY_DESCRIPTION: 'Upload a CSV with species, quantities, and other fields.',
  IMPORT_INVENTORY_WITH_TEMPLATE: 'Import inventory using our CSV template.',
  IMPORT_INVENTORY: 'Import Inventory',
  IMPORT_SPECIES_DESCRIPTION: 'Upload a CSV with scientific names and other optional fields.',
  IMPORT_SPECIES_LIST_DESC: 'Browse or drag and drop a CSV with scientific names and other optional fields.',
  IMPORT_SPECIES_LIST: 'Import Species List',
  IMPORT_SPECIES: 'Import Species',
  IMPORT: 'Import',
  IMPORTING_ACCESSIONS: 'Importing accessions... this may take a few minutes.',
  IMPORTING_INVENTORY: 'Importing inventory...this may take a few minutes.',
  IMPORTING_SPECIES: 'Importing species...this may take a few minutes.',
  INCLUDE_EMPTY_FIELDS: 'Include empty fields',
  INCORRECT_EMAIL_FORMAT: 'Incorrect email format.',
  IN_STORAGE: 'In Storage',
  INITIAL_SEEDS: 'Initial Seeds',
  INTERMEDIATE: 'Intermediate',
  INVALID_DATE: 'Invalid date',
  INVALID_VALUE: 'Invalid Value',
  INVENTORY_DATA: 'Inventory Data',
  INVENTORY_IMPORT_COMPLETE: 'Inventory data import complete!',
  INVENTORY_ONBOARDING_NURSERIES_MSG: 'Define nurseries assigned to seedlings inventory',
  INVENTORY_ONBOARDING_SPECIES_MSG: 'Define a list of species used in your seedlings inventory',
  INVENTORY: 'Inventory',
  ISSUE: 'Issue',
  KEEP_ORIGINAL: 'Keep Original',
  KEY_BELONGS_TO_ANOTHER_SEED_BANK: 'Key is associated with another seed bank.',
  KEY_WAS_NOT_RECOGNIZED: 'Key was not recognized.',
  KG_KILOGRAMS: 'kg (kilograms)',
  KG: 'kg',
  KILOGRAMS: 'Kilograms',
  LAB_DESCRIPTION: 'All the details about lab viability tests conducted on the seeds.',
  LAB_GERMINATION: 'Lab Germination',
  LAB: 'Lab',
  LANDOWNER: 'Landowner',
  LANGUAGE: 'Language',
  LANGUAGE_AND_REGION: 'Language and Region',
  LAST_NAME: 'Last Name',
  LATITUDE_LONGITUDE: 'Latitude, Longitude',
  LB_POUNDS: 'lb (pounds)',
  LB: 'lb',
  LEARN_MORE_CONSERVATION_STATUS_ENDANGERED:
    'Species that are rare and whose wild populations have a high risk of extinction; see also any local definitions.',
  LEARN_MORE_CONSERVATION_STATUS_RARE:
    'Species with limited wild population sizes, often found in isolated geographical locations; may meet criteria for endangered or threatened status but have not yet been legally listed or assessed.',
  LEARN_MORE_GROWTH_FORM_FERN:
    'A non-flowering vascular plant that reproduces by spores, in the plant division Pteridophyta.',
  LEARN_MORE_GROWTH_FORM_FORB: 'A herbaceous (non-woody) plant that is NOT a graminoid (grass, sedge, or rush).',
  LEARN_MORE_GROWTH_FORM_GRAMINOID:
    'A herbaceous (non-woody) plant with a grass-like morphology, that is elongated culms with long, blade-like leaves, in the grass, sedge, or rush family.',
  LEARN_MORE_GROWTH_FORM_SHRUB:
    'A woody plant which is smaller than a tree and has several main stems arising at or near the ground.',
  LEARN_MORE_GROWTH_FORM_TREE:
    'A woody perennial plant, typically having a single stem or trunk growing to a considerable height and bearing lateral branches at some distance from the ground.',
  LEARN_MORE_SEED_STORAGE_BEHAVIOR_INTERMEDIATE:
    'Seeds are between orthodox and recalcitrant seeds in their behavior; may include tolerating partial desiccation, tolerating cool but not freezing temperatures, or being short-lived regardless of storage conditions.',
  LEARN_MORE_SEED_STORAGE_BEHAVIOR_ORTHODOX:
    'Seeds tolerate levels of desiccation required for frozen storage (5-8% moisture content) and temperatures of -20°C or lower.',
  LEARN_MORE_SEED_STORAGE_BEHAVIOR_RECALCITRANT:
    'Seeds do not tolerate levels of desiccation required for ex situ (off-site) conservation.',
  LEARN_MORE: 'Learn more',
  LEAVE_AND_SAVE: 'Leave and Save',
  LEAVE_ORGANIZATION: 'Leave Organization',
  LESS_THAN_A_MONTH: '<1 month',
  LESS_THAN_ONE: '<1',
  LIGHT: 'Light',
  LIST_SEPARATOR_SECONDARY: '; ',
  LIST_SEPARATOR: ', ',
  LOADING: 'Loading...',
  LOCATION_REQUIRED: 'Location *',
  LOCATION: 'Location',
  LOCATIONS: 'Locations',
  LOG_OUT: 'Log Out',
  LOSS_RATE: 'Loss Rate',
  MANAGER: 'Manager',
  MANAGER_INFO: 'A manager can do the above as well as edit data entries for seeds and manage species.',
  MARK_ALL_AS_READ: 'Mark All As Read',
  MARK_AS_COMPLETE: 'Mark as Complete',
  MARK_AS_READ: 'Mark As Read',
  MARK_AS_UNREAD: 'Mark As Unread',
  MAX: 'Max',
  MEDIA_MIX: 'Media Mix',
  METRIC: 'Metric',
  METRIC_G_KG_MG: 'Metric (g, kg, mg)',
  MG_MILLIGRAMS: 'mg (milligrams)',
  MG: 'mg',
  MIDDLE_OF_SEED_BANK: 'Middle of Seed Bank',
  MILLIGRAMS: 'Milligrams',
  MIN: 'Min',
  MISSING_SUBSET_WEIGHT_ERROR_NURSERY:
    'You must enter in a subset weight in order to withdraw to a nursery. This can be done by editing the quantity of this accession.',
  MISSING_SUBSET_WEIGHT_ERROR_VIABILITY_TEST:
    'You must enter in a subset weight in order to create a viability test. This can be done by editing the quantity of this accession.',
  MONITORING_CARD_DESCRIPTION:
    'Add seed banks to your organization and then monitor things like temperature and humidity through their sensor kits.',
  // https://date-fns.org/v2.29.3/docs/format
  MONITORING_DATE_FORMAT: 'MMM d h:mmaaa',
  MONITORING_LABEL_HUMIDITY: 'Humidity',
  MONITORING_LABEL_HUMIDITY_THRESHOLDS: 'Humidity Thresholds',
  MONITORING_LABEL_STATE_OF_CHARGE: 'State of Charge',
  MONITORING_LABEL_SYSTEM_POWER: 'System Power',
  MONITORING_LABEL_TEMPERATURE: 'Temperature',
  MONITORING_LABEL_TEMPERATURE_THRESHOLDS: 'Temperature Thresholds',
  MONITORING: 'Monitoring',
  MONTH: 'Month',
  MONTHS: 'Months',
  MOSS: 'Moss',
  MOST_RECENT_PERCENTAGE_VIABILITY: 'Most Recent % Viability',
  MOVE: 'Move',
  MY_ACCOUNT_DESC: 'Manage your account information.',
  MY_ACCOUNT_NOTIFICATIONS_DESC:
    'Notifications alert you when there are important updates about your organizations. You will receive them through email.',
  MY_ACCOUNT: 'My Account',
  NAME_REQUIRED: 'Name *',
  NAME_UNKNOWN: '(name unknown)',
  NAME: 'Name',
  NATIVE_FOREST_RESTORATION: 'Native Forest Restoration',
  NEW_ACCESSION_DESCRIPTION: 'An accession number will be generated once you create the accession.',
  NEW_ACCESSION_INFO:
    'Information like Seed Bags, Photos and Geolocations can only be added via the Seed Collector Android app. All the other information about processing, drying, storage and withdrawals can be added after first creating the accession.',
  NEW_ACCESSION: 'Add Accession',
  NEW_APP_VERSION_MOBILE: 'Refresh for the latest Terraware version.',
  NEW_APP_VERSION: 'Please refresh to use the latest version of Terraware.',
  NEW_ENTRY: 'New Entry',
  NEW_PLOT: 'New Plot',
  NEW_SPECIES: 'New Species',
  NEW_TEST: 'New Test',
  NEW_WITHDRAWAL: 'New Withdrawal',
  NEXT_ARROW: 'Next >',
  NEXT_PROCESSING_AND_DRYING: 'Next: Processing & Drying',
  NEXT_STORING: 'Next: Storing',
  NEXT_WITHDRAWAL: 'Next: Withdrawal',
  NEXT: 'Next',
  NICE: 'Nice!',
  NO_BATCHES_TO_WITHDRAW_FROM: 'There are no batches with withdrawable quantities.',
  NO_DATA_YET: 'No data yet',
  NO_FUTURE_DATES: 'No future dates allowed',
  NO_INVENTORY_DESCRIPTION:
    'It looks like you haven’t added inventory yet. You can either import data from a CSV file, or add inventory using our inventory form.',
  NO_MOBILE_SUPPORT_DESC: 'Please access terraware.io on a desktop device.',
  NO_MOBILE_SUPPORT_TITLE: 'Terraware web doesn’t support mobile yet.',
  NO_NEGATIVE_NUMBERS: 'No negative numbers allowed',
  NO_NOTIFICATIONS: 'No notifications to show.',
  NO_NURSERIES_NON_ADMIN_MSG:
    'Before you can add and manage your nursery inventory, you’ll need to have a nursery and species within Terraware. Only admins can add nurseries and species, so please reach out to yours for assistance.',
  NO_PAST_DATES: 'No past dates allowed',
  NO_PEOPLE_IN_ORG: 'No People in Organization',
  NO_PLANTS: 'No Plants',
  NO_REASSIGNMENTS_TEXT: 'Select a new plot with quantity in at least one seedlings batch row.',
  NO_REASSIGNMENTS: 'No Reassignments',
  NO_SEEDBANKS_ADMIN_MSG: 'Start by adding a seed bank. You’ll then be able to access and create new accessions.',
  NO_SEEDBANKS_ADMIN_TITLE: 'Just a moment, let’s add a seed bank first.',
  NO_SEEDBANKS_MONITORING_ADMIN_MSG:
    "Start by adding a seed bank. If your seed bank was built by Terraformation, you’ll then be able to monitor things like the seed bank's temperature and humidity.",
  NO_SEEDBANKS_MONITORING_NON_ADMIN_MSG:
    'Before you can begin remotely monitoring things like temperature and humidity through a seed bank’s sensor kit, you’ll need to add a seed bank within Terraware. Only admins can add seed banks, so please reach out to yours for assistance.',
  NO_SEEDBANKS_NON_ADMIN_MSG:
    'Before you can add and manage your accessions, you’ll need to have a seed bank and species within Terraware. Only admins can add seed banks and species, so please reach out to yours for assistance.',
  NO_SEEDBANKS_SET_UP_NON_ADMIN_MSG:
    "If your seed bank was built by Terraformation, it is equipped with a sensor kit that you can remotely monitor things like the seed bank's temperature and humidity. Your seed bank either does not have a sensor kit, or it has not yet been set up by your administrator.",
  NO_SEEDLINGS_AVAILABLE_TO_OUTPLANT_DESCRIPTION:
    'There are no batches selected with seedlings that are "ready." Select another withdraw purpose or cancel and select a different batch.',
  NO_SEEDLINGS_AVAILABLE_TO_OUTPLANT_TITLE: 'No Seedlings Available to Outplant',
  NO_SPECIES_CONTRIBUTOR_MSG:
    'There are no species in your species list yet. Only admins can add species, so please reach out to yours for assistance.',
  NO_SPECIES_DESCRIPTION:
    'It looks like you haven’t added any species yet. Having a master species list helps streamline your organization’s seed and plant data entry. You can either add species manually and individually, or import data from a CSV.',
  NO: 'No',
  NONE: 'None',
  NOT_CONNECTED: 'Not Connected',
  NOT_READY_QUANTITY_REQUIRED: 'Not Ready Quantity *',
  NOT_READY_QUANTITY: 'Not Ready Quantity',
  NOT_READY: 'Not Ready',
  NOTES: 'Notes',
  NOTIFICATIONS: 'Notifications',
  NUMBER_OF_PACKETS: 'Number of Packets',
  NUMBER_OF_PEOPLE: 'Number of People',
  NUMBER_OF_PLANTS_BY_PLOT_AND_SPECIES: 'Number of Plants by Plot and Species',
  NUMBER_OF_PLANTS_BY_SPECIES: 'Number of Plants by Species',
  NUMBER_OF_PLANTS: 'Number of Plants',
  NUMBER_OF_SEEDS_COMPROMISED_REQUIRED: '# Seeds Compromised *',
  NUMBER_OF_SEEDS_COMPROMISED_V2: '# Seeds Compromised',
  NUMBER_OF_SEEDS_COMPROMISED: 'Number of Seeds Compromised',
  NUMBER_OF_SEEDS_EMPTY_REQUIRED: '# Seeds Empty *',
  NUMBER_OF_SEEDS_EMPTY_V2: '# Seeds Empty',
  NUMBER_OF_SEEDS_EMPTY: 'Number of Seeds Empty',
  NUMBER_OF_SEEDS_FILLED_REQUIRED: '# Seeds Filled *',
  NUMBER_OF_SEEDS_FILLED_V2: '# Seeds Filled',
  NUMBER_OF_SEEDS_FILLED: 'Number of Seeds Filled',
  NUMBER_OF_SEEDS_GERMINATED_REQUIRED: '# Seeds Germinated *',
  NUMBER_OF_SEEDS_GERMINATED: '# Seeds Germinated',
  NUMBER_OF_SEEDS_IN_SUBSET: '# of Seeds in Subset',
  NUMBER_OF_SEEDS_SOWN: 'Number of Seeds Sown',
  NUMBER_OF_SEEDS_TESTED_REQUIRED: '# Seeds Tested *',
  NUMBER_OF_SEEDS_TESTED: '# Seeds Tested',
  NUMBER_OF_SEEDS_WITHDRAWN: 'Seeds Withdrawn',
  NUMBER_OF_SPECIES: 'Number Of Species',
  NUMBER_PLANTS_COLLECTED_FROM: 'Number of plants collected from',
  NURSERIES: 'Nurseries',
  NURSERY_ADDED: 'Nursery Added',
  NURSERY_DESCRIPTION: 'All the details about nursery viability tests conducted on the seeds.',
  NURSERY_GERMINATION: 'Nursery Germination',
  NURSERY_MEDIA: 'Nursery Media',
  NURSERY_REQUIRED: 'Nursery *',
  NURSERY_TRANSFER: 'Nursery Transfer',
  NURSERY: 'Nursery',
  ONBOARDING_ADMIN_TITLE: 'Just a moment, let’s complete setup first',
  OPT_IN: 'Opt-In Features',
  OR_SEED_WEIGHT: 'or Seed Weight',
  OR: 'OR',
  ORGANIZATION_CREATE_FAILED: 'Unable to create organization.',
  ORGANIZATION_CREATED_MSG:
    'You can access the organizations you’re in by clicking the arrow in the top right corner next to your profile.',
  ORGANIZATION_CREATED_TITLE: 'You have created {0}!',
  ORGANIZATION_DATA_NOT_AVAILABLE: 'Organization Data Not Available',
  ORGANIZATION_DESC: 'Manage your organization.',
  ORGANIZATION_NAME_REQUIRED: 'Organization Name *',
  ORGANIZATION_NAME: 'Organization Name',
  ORGANIZATION: 'Organization',
  ORGANIZATIONS: 'Organizations',
  ORIGINAL_PLOT: 'Original Plot',
  ORIGINAL_QTY: 'Original Qty',
  ORTHODOX: 'Orthodox',
  OTHER: 'Other',
  OUNCES: 'Ounces',
  OUT_PLANTING: 'Out-planting',
  OUTPLANT: 'Outplant',
  OUTPLANTS_REQUIRE_READY_SEEDLINGS: 'Outplants require batches with seedlings that are "ready."',
  OWNER: 'Owner',
  OZ_OUNCES: 'oz (ounces)',
  OZ: 'oz',
  PAGINATION_FOOTER: '{0} to {1} of {2}',
  PAGINATION_FOOTER_EMPTY: '0 of 0',
  PAPER_PETRI_DISH: 'Paper Petri Dish',
  PAPER: 'Paper',
  PENDING: 'Pending',
  PEOPLE_CARD_DESCRIPTION: 'We can’t do it alone! Add people to your Organization and assign them roles.',
  PEOPLE_DESCRIPTION: 'Manage the people in Terraware.',
  PEOPLE: 'People',
  PERCENTAGE_VALUE: '{0}%',
  PERCENTAGE_VIABILITY: '% Viability',
  PERIOD_LAST_12_HOURS: 'Last 12 hours',
  PERIOD_LAST_24_HOURS: 'Last 24 hours',
  PERIOD_LAST_30_DAYS: 'Last 30 days',
  PERIOD_LAST_7_DAYS: 'Last 7 days',
  PERLITE_VERMICULITE: 'Perlite/Vermiculite',
  PERSON_ADDED: 'Person Added',
  PHOTOS_OUTPLANT_DESCRIPTION: 'Outplant withdrawals require photos.',
  PHOTOS_REQUIRED: 'Photos Required',
  PHOTOS: 'Photos',
  PLANT_DESCRIPTION: 'Plant Description',
  PLANT_DETAIL: 'Plant Detail',
  PLANT_ID_TOOLTIP:
    'It’s the ID of a plant for tracking or conservation purpose. Ideally seeds from a tracked plant do not mix with others in a same accession.',
  PLANT_ID: 'Plant ID',
  PLANT_LABEL: 'Plant',
  PLANT: 'plant',
  PLANTING_SITE_TYPE: 'Planting Site Type',
  PLANTING_SITE_WITH_MAP_HELP:
    'If you are a Terraformation partner or accelerator participant, please [contact us] to create a site with a map.',
  PLANTING_SITE: 'Planting Site',
  PLANTING_SITES: 'Planting Sites',
  PLANTING_ZONE: 'Planting Zone',
  PLANTING_ZONES: 'Planting Zones',
  PLANTS_CARD_DESCRIPTION: 'They’ve taken root! View all your plants in one place.',
  PLANTS: 'Plants',
  PLEASE_TRY_AGAIN: 'Please try again.',
  PLOT_REQUIRED: 'Plot *',
  PLOT: 'Plot',
  PLOTS: 'Plots',
  POUNDS: 'Pounds',
  PREEXISTING_SPECIES: 'This species already exists',
  PREFERRED_WEIGHT_SYSTEM: 'Preferred Weight System',
  PREVIOUS_ARROW: '< Pevious',
  PRIVACY_POLICY: 'Privacy Policy',
  PROBLEMS: 'Problems',
  PROCESSED_AND_DRIED_BY: 'Processed & Dried By',
  PROCESSING_AND_DRYING_DESCRIPTION: 'All the details about processing and drying the seeds.',
  PROCESSING_AND_DRYING_INFO:
    'By adding information about processing/drying and saving changes, you will be automatically changing this accession’s stage from Pending to either Processing, Processed, Drying, or Dried, depending on the information you fill in.',
  PROCESSING_AND_DRYING: 'Processing & Drying',
  PROCESSING_METHOD: 'Processing Method',
  PROCESSING_START_DATE: 'Processing Start Date',
  PROCESSING_STATUS_REQUIRED: 'Processing Status *',
  PROCESSING: 'Processing',
  PURPOSE_REQUIRED: 'Purpose *',
  PURPOSE: 'Purpose',
  PV_BATTERY_CHARGE: 'PV Battery Charge',
  PV_BATTERY: 'PV Battery',
  PV_SYSTEM: 'PV system',
  QUANTIFY: 'Quantify',
  QUANTITY: 'Quantity',
  RARE_ENDANGERED: 'Rare, Endangered',
  RARE: 'Rare',
  REACH_OUT_TO_ADMIN_TITLE: 'Please reach out to an administrator from your organization.',
  READY_QUANTITY_REQUIRED: 'Ready Quantity *',
  READY_QUANTITY: 'Ready Quantity',
  READY: 'Ready',
  REASSIGN_SEEDLINGS_DESCRIPTION:
    'Enter the new plot, new quantity, and notes for the species you want to reassign seedlings for. The seedlings for rows you leave empty will not be reassigned.',
  REASSIGN_SEEDLINGS: 'Reassign Seedlings',
  REASSIGN: 'Reassign',
  REASSIGNMENT: 'Reassignment',
  RECALCITRANT: 'Recalcitrant',
  RECEIVE_EMAIL_NOTIFICATIONS: 'Receive Email Notifications',
  RECEIVED_DATE: 'Received Date',
  RECEIVED_ON: 'Received On',
  RECEIVING_DATE_REQUIRED: 'Receiving Date *',
  RECEIVING_NURSERY_REQUIRED: 'Receiving Nursery *',
  RECORDING_DATE_ERROR: 'This should be later than Start Date',
  RECORDING_DATE: 'Recording Date',
  REFRESH_DATA: 'Refresh Data',
  REFRESH: 'Refresh',
  REINTRODUCED_DESCRIPTION:
    'Plants that have been transplanted from a nursery, greenhouse, or other location to a restoration site.',
  REINTRODUCED: 'Reintroduced',
  REMAINING_UNITS: 'Remaining Units',
  REMAINING: 'Remaining',
  REMINDER_DATE: 'Reminder Date',
  REMOVE_AND_SAVE: 'Remove & Save',
  REMOVE_ONLY_ONE_ORG_AT_A_TIME: 'You may only remove yourself from one organization at a time.',
  REMOVE_PEOPLE_DESC:
    'Are you sure you want to remove these people? Removing these people means they won’t have access to your organization’s data anymore.',
  REMOVE_PEOPLE: 'Remove People',
  REMOVE_PERSON_DESC:
    'Are you sure you want to remove {0}? Removing {0} means they won’t have access to your organization’s data anymore.',
  REMOVE_PERSON: 'Remove Person',
  REMOVE: 'Remove',
  REMOVED_PEOPLE_WARNING_DESC: 'The people you’ve removed include',
  REMOVING_ORG_WARNING:
    'Removing yourself from {0} means you won’t have access to this organization’s data anymore. Are you sure you want to save your changes?',
  REPLACE_FILE: 'Replace File...',
  REPLACE: 'Replace',
  REPORT_NAME: 'Report Name',
  REPORT_PROBLEM: 'Report Problem',
  REPORT: 'Report',
  REQUEST_FEATURE: 'Request Feature',
  REQUIRED_FIELD: 'Required field.',
  RESET: 'Reset',
  REVIEW_ERRORS: 'Review Errors',
  ROLE_REQUIRED: 'Role *',
  ROLE: 'Role',
  ROLES_INFO: 'Select a role for this person.',
  ROWS_SELECTED: '{0} selected',
  RUN_A_DATABASE_CHECK: 'Run a Database Check',
  S_SEED_COUNT: 'seed count',
  SAND_PETRI_DISH: 'Sand Petri Dish',
  SAND: 'Sand',
  SAVE_ACCESSION_ERROR: 'An error occurred when saving the accession.',
  SAVE_CHANGES: 'Save Changes',
  SAVE: 'Save',
  SAVING: 'Saving...',
  SCARIFY: 'Scarify',
  SCHEDULE_DATE_INFO: 'Schedule a date by selecting a future date.',
  SCHEDULE_DATE_TO_MOVE: 'Schedule Date to Move from Racks to Dry Cabinets',
  SCHEDULE_WITHDRAWAL: 'Schedule Withdrawal',
  SCHEDULED_FOR_TESTING: 'Scheduled for Testing',
  SCHEDULED_FOR: 'Scheduled for',
  SCHEDULED_SEEDS: '{0} Seeds',
  SCHEDULED: '(Scheduled)',
  SCHEDULING_FOR: 'Scheduling for: {0}',
  SCIENTIFIC_NAME_NOT_FOUND: '“{0}” was not found in our database, but you can still add it.',
  SCIENTIFIC_NAME_REQUIRED: 'Scientific Name *',
  SCIENTIFIC_NAME: 'Scientific Name',
  SEARCH_BY_NAME_OR_FAMILY: 'Search by name or family...',
  SEARCH_OR_SELECT: 'Search or Select...',
  SEARCH: 'Search',
  SEE_ALL_ACCESSIONS: 'See All Accessions',
  SEE_ENTRIES: 'See Entries',
  SEED_BAGS: 'Seed Bags',
  SEED_BANK_ADDED: 'Seed Bank added.',
  SEED_BANK_INTERNET: 'Seed Bank Internet',
  SEED_BANK: 'Seed Bank',
  SEED_BANKS_CARD_DESCRIPTION: 'How do you process and store your seeds? Add seed banks to your organization.',
  SEED_BANKS: 'Seed Banks',
  SEED_COLLECTION_DESCRIPTION: 'All the details about the species, date collected, collectors and the site location.',
  SEED_COLLECTION_DETAIL_DESC: 'Enter this accession’s seed information below.',
  SEED_COLLECTION_DETAIL: 'Seed Details',
  SEED_COLLECTION: 'Seed Collection',
  SEED_COUNT: 'Seed Count',
  SEED_DASHBOARD: 'Seed Dashboard',
  SEED_STORAGE_BEHAVIOR: 'Seed Storage Behavior',
  SEED_TYPE: 'Seed Type',
  SEED_WEIGHT: 'Seed Weight',
  SEED: 'Seed',
  SEEDLING_BATCH_DETAILS: 'Seedling Batch Details',
  SEEDLING_BATCH: 'Seedling Batch',
  SEEDLINGS_BATCHES: 'Seedlings Batches',
  SEEDLINGS_PLURAL: 'seedlings',
  SEEDLINGS_SINGULAR: 'seedling',
  SEEDLINGS: 'Seedlings',
  SEEDS_GERMINATED_LC: 'seeds germinated',
  SEEDS_GERMINATED: 'Seeds Germinated',
  SEEDS_REMAINING: 'Seeds Remaining',
  SEEDS_SOWN: 'Seeds Sown',
  SEEDS_UNITS: 'Units Quantity of Seeds',
  SEEDS: 'Seeds',
  SELECT_BATCHES: 'Select Batches',
  SELECT_BUTTON: 'Select',
  SELECT_PLANTING_SITE_TYPE_DESCRIPTION_1: 'Please select which type of planting site to add.',
  SELECT_PLANTING_SITE_TYPE_DESCRIPTION_2:
    'Sites with maps allow you to track the location of plants within the site and perform live/dead monitoring. Sites without maps allow you to track how many and which species of plants have been planted on the site.',
  SELECT_PLANTING_SITE_TYPE_DESCRIPTION_3:
    'Please note that if you create a site without a map, you won’t be able to add a map to it later on.',
  SELECT_PLANTING_SITE_TYPE: 'Select Planting Site Type',
  SELECT_SEED_BANK_INFO: 'Accessions require a seed bank storage location. Please select a seed bank.',
  SELECT_SEED_BANK: 'Select Seed Bank',
  SELECT: 'Select...',
  SEND_TO_NURSERY: 'Send to Nursery',
  SENDING: 'Sending...',
  SENSOR_KIT_HAS_BEEN_SET_UP: 'Sensor Kit has been set up. Go to the {0} page to see them.',
  SENSOR_KIT_ID_PLACEHOLDER: 'XXXXXX',
  SENSOR_KIT_READY_TO_SET_UP:
    'If you have a Terraformation seed bank, its sensor kit is ready to be set up. Take me to the {0} page to set it up.',
  SENSOR_KIT_SET_UP_COMPLETE_DESCRIPTION:
    'You will now be able to view solar battery charge and sensor data in your sensor monitoring dashboard.',
  SENSOR_KIT_SET_UP_COMPLETE: 'Setup Complete!',
  SENSOR_KIT_SET_UP_DESCRIPTION: "If your seed bank has a sensor kit, let's set it up below.",
  SENSOR_KIT_SET_UP_DETECT_SENSORS_DESCRIPTION:
    "To power on sensors, remove the paper tabs blocking the batteries. When sensors are powered on and within range, they'll be detected by the device manager automatically.",
  SENSOR_KIT_SET_UP_DETECT_SENSORS: 'Detect Sensors',
  SENSOR_KIT_SET_UP_DEVICE_MANAGER_DESCRIPTION:
    'To detect your sensors, the device manager in your sensor kit needs to download the latest code; this may take up to 20 minutes. The download starts the moment your sensor kit is connected to the internet, so this step might alread be complete.',
  SENSOR_KIT_SET_UP_DEVICE_MANAGER: 'Install Device Manager Update',
  SENSOR_KIT_SET_UP_PV_SYSTEM_DESCRIPTION:
    'Our seed banks support multiple types of PV systems; select which one you have so that we can accurately display battery charge.',
  SENSOR_KIT_SET_UP_PV_SYSTEM: 'Select PV System',
  SENSOR_KIT_SET_UP_SENSOR_KIT_ID_DESCRIPTION:
    'Find your sensor kit ID on the outside of your sensor kit. This will connect the Device Manager inside the kit to our database.',
  SENSOR_KIT_SET_UP_SENSOR_KIT_ID: 'Enter Sensor Kit ID',
  SENSOR_KIT_SET_UP_SENSOR_LOCATIONS_DESCRIPTION:
    'Your sensor kit includes 14 temperature/humidity sensors. Please put one sensor in each location. Select which sensor you put in each location using the dropdown.',
  SENSOR_KIT_SET_UP_SENSOR_LOCATIONS: 'Assign Sensor Locations',
  SENSOR_KIT_SET_UP_TIME: 'This may take up to 30 minutes.',
  SENSOR_KIT_SET_UP_TITLE: "Let's Set Up Your Sensor Kit!",
  SENSOR_KIT: 'Sensor Kit',
  SENSOR_LOCATION_ERROR: 'Each location much have one sensor assigned to it.',
  SENSOR_SCAN_TIMEOUT_ERROR:
    "Only {0}/{1} sensors were found. Please make sure all sensors are powered on and within range, then try again. If this problem persists, you might have broken sensors; if you think that's the case, email us at {2}.",
  SENSOR_SCAN_TIMEOUT: 'Sensor Scan Timeout',
  SENSORS_FOUND: '{0}/{1} sensors found...',
  SENT_TO_NURSERY: 'Sent to Nursery!',
  SERVER_ERROR: 'Server Error',
  SET_UP_YOUR_SENSOR_KIT_MSG:
    "If your seed bank was built by Terraformation, it is equipped with a sensor kit that you can remotely monitor things like the seed bank's temperature and humidity. To set this up, you'll need to connect your seed bank to the Terraware web app. This may take up to 30 minutes.",
  SET_UP_YOUR_SENSOR_KIT: 'Set Up Your Sensor Kit',
  SET_UP: 'Set Up',
  SETTINGS: 'Settings',
  SHRUB: 'Shrub',
  SILVOPASTURE: 'Silvopasture',
  SITE_DETAIL: 'Site Detail',
  SITE_LOCATION: 'Site Location',
  SITE: 'Site',
  SNACKBAR_MSG_CHANGES_SAVED: 'Changes saved just now.',
  SNACKBAR_MSG_NEW_SPECIES_ADDED: 'New species added just now.',
  SNACKBAR_MSG_PLANT_DELETED: 'Plant deleted just now.',
  SNACKBAR_MSG_SPECIES_DELETED: 'Species deleted just now.',
  SOAK: 'Soak',
  SOIL: 'Soil',
  SOMETHING_WENT_WRONG_MESSAGE:
    'If you’re having trouble using Terraware, please report any issues you’re having and we’ll make it right.',
  SOMETHING_WENT_WRONG_TITLE: 'Something went wrong...',
  SOMETHING_WENT_WRONG: 'Something went wrong.',
  SOWN: 'Sown',
  SPECIES_CARD_DESCRIPTION: 'View the Species that are referenced by your Seed and Plant entries.',
  SPECIES_DATA_NOT_AVAILABLE: 'Species Data Not Available',
  SPECIES_DESCRIPTION: 'Manage your organization’s species list for planning, operation and reporting.',
  SPECIES_EMPTY_MSG_BODY:
    'Enter species that you collect or plant now to simplify your experience when you’re out in the field.',
  SPECIES_ERROR_SEARCH: "Couldn't load species list for search",
  SPECIES_IMPORT_COMPLETE: 'Species data import complete!',
  SPECIES_NAME: 'Species Name',
  SPECIES_PROBLEM_NAME_IS_SYNONYM: 'Name Is Synonym',
  SPECIES_PROBLEM_NAME_MISSPELLED: 'Name Misspelled',
  SPECIES_PROBLEM_NAME_NOT_FOUND: 'Name Not Found',
  SPECIES_REQUIRED: 'Species *',
  SPECIES_SELECTED: 'Species Selected',
  SPECIES: 'Species',
  STAFF_RESPONSIBLE: 'Staff Responsible',
  STAFF: 'Staff',
  STAGE: 'Stage',
  START_DATE_REQUIRED: 'Start Date *',
  START_DATE: 'Start Date',
  START_SET_UP: 'Start Setup',
  START_TESTING: 'Start Testing',
  START: 'Start',
  STARTING_ON: 'Starting On',
  STATE_PROVINCE_REGION: 'State/Province/Region',
  STATE_REQUIRED: 'State *',
  STATE: 'State',
  STATUS: 'Status',
  STORAGE_CONDITION: 'Storage Condition',
  STORAGE_DESCRIPTION: 'All the details about storing the seeds.',
  STORAGE_INFO:
    'By adding information about storage and saving changes, you will be automatically changing this accession’s stage from Pending to Stored.',
  STORAGE_LOCATION: 'Storage Location',
  STORAGE: 'Storage',
  STORED_BY: 'Stored By',
  STORED_SEEDS: 'Stored Seeds',
  STORED: 'Stored',
  STORING: 'Storing',
  STORING_START_DATE: 'Storing Start Date',
  STRATIFICATION: 'Stratification',
  SUB_LOCATION: 'Sub-Location',
  SUBSET_COUNT: 'Subset Count',
  SUBSET_ERROR: 'Subset weight should be less than seed weight',
  SUBSET_WEIGHT: 'Weight of Seed Subset',
  SUBSTRATE: 'Substrate',
  SUBTITLE_GET_STARTED:
    "To get started, please create your organization now. You'll also be able to set up and manage information on people and species.",
  SUGGESTION: 'Suggestion',
  SUMMARY: 'Summary',
  SUSTAINABLE_TIMBER: 'Sustainable Timber',
  TAKE_ME_THERE: 'Take Me There',
  TARGET_RH: 'Target %RH',
  TEMPERATURE_AND_HUMIDITY_SENSOR_DATA: 'Temperature & Humidity Sensor Data',
  TEMPLATES: 'Templates',
  TEST_DATE_REQUIRED: 'Test Date *',
  TEST_METHOD_REQUIRED: 'Test Method *',
  TEST_METHOD: 'Test Method',
  TEST_TYPE: 'Test Type',
  TEST: 'Test',
  TESTING_STAFF: 'Testing Staff',
  TIME_PERIOD: 'Time Period',
  TIME_ZONE_INITIALIZED_TITLE: 'Time Zone Set',
  TIME_ZONE_INITIALIZED_ORG_MESSAGE:
    "Your organization's time zone was updated to {0} zone. You can edit this setting from Settings > {1}.",
  TIME_ZONE_INITIALIZED_USER_MESSAGE: 'Your time zone was updated to {0} zone. You can edit this setting from {1}.',
  TIME_ZONE_INITIALIZED_USER_ORG_MESSAGE:
    "Your organization's and your time zone was updated to {0} zone. You can edit this setting from Settings > {1} and {2} respectively.",
  TIME_ZONE_REQUIRED: 'Time Zone *',
  TIME_ZONE: 'Time Zone',
  TITLE_REPORT_PROBLEM: 'Report a Problem',
  TITLE_REQUEST_FEATURE: 'Request a Feature',
  TITLE_TEST_APP: 'Test our Mobile App',
  TITLE_WELCOME: 'Welcome to Terraware',
  TRUNCATED_TEXT_MORE_LINK: 'more',
  TRUNCATED_TEXT_MORE_SEPARATOR: '...',
  TO_NURSERY_REQUIRED: 'To: Nursery *',
  TO_PLANTING_SITE_REQUIRED: 'To: Planting Site *',
  TO_PLOT: 'To: Plot',
  TO: 'To',
  TOOLTIP_ACCESSIONS_ADD_COLLECTING_SITE:
    'The place where seeds were collected. It is recommended to name these referencing stable landmarks or features that do not change.',
  TOOLTIP_ACCESSIONS_ADD_PLANT_ID:
    'The unique identifier given to a plant for tracking or conservation purposes. Ideally seeds from a plant with a plant ID are kept separate from other plants (not pooled together) in collections and accessions.',
  TOOLTIP_ACCESSIONS_COLLECTION_SOURCE: 'The type of plant population where seeds are collected.',
  TOOLTIP_ACCESSIONS_ID:
    'A unique identifier for a seed collection accepted into a seed bank. Any collection from a new species, location, and/or date would typically become a new accession in the seed bank.',
  TOOLTIP_ACCESSIONS_LOCATION: 'Place where seeds are being processed.',
  TOOLTIP_ACCESSIONS_SUBLOCATION: 'Specific area within the place where seeds are being processed.',
  TOOLTIP_COMMON_NAME: 'The name an organism is known by to the general public, rather than its scientific name.',
  TOOLTIP_DASHBOARD_TOTAL_ACTIVE_ACCESSIONS:
    'This number represents all accessions with the statuses awaiting processing, cleaning, drying, and in storage.',
  TOOLTIP_ECOSYSTEM_TYPE:
    'Relatively large units of land or water containing a distinct assemblage of natural communities sharing a large majority of species, dynamics, and environmental conditions.',
  TOOLTIP_GERMINATING_QUANTITY:
    'Germinating indicates that seedlings have not yet emerged from seeds. Germinating quantity does not count toward the total quantity.',
  TOOLTIP_NOT_READY_QUANTITY:
    'What determines a plant as “not ready” is up to your team and is often species specific. For example: size of plant or amount of time acclimated.',
  TOOLTIP_READY_QUANTITY:
    'What determines a plant as “ready” is up to your team and is often species specific. For example: size of plant or amount of time acclimated.',
  TOOLTIP_SCIENTIFIC_NAME: 'The binomial Latin name (genus + species) currently accepted in the botanical literature.',
  TOOLTIP_SPECIES_CONSERVATION_STATUS:
    "A species' risk of extinction, usually a legal designation or a Red List assessment.",
  TOOLTIP_SPECIES_FAMILY: 'The scientific name of the plant family currently accepted in the botanical literature.',
  TOOLTIP_SPECIES_GROWTH_FORM:
    'A structural category consisting of individuals or species of the same general habit of growth but not necessarily related.',
  TOOLTIP_SPECIES_SEED_STORAGE_BEHAVIOR:
    'The capacity of seeds to survive desiccation and temperatures to levels necessary for ex site (off site) storage.',
  TOOLTIP_TIME_ZONE_MY_ACCOUNT: 'Lorem ipsum...',
  TOOLTIP_TIME_ZONE_NURSERY: 'Lorem ipsum...',
  TOOLTIP_TIME_ZONE_ORGANIZATION: 'Lorem ipsum...',
  TOOLTIP_TIME_ZONE_PLANTING_SITE: 'Lorem ipsum...',
  TOOLTIP_TIME_ZONE_SEEDBANK: 'Lorem ipsum...',
  TOOLTIP_TOTAL_QUANTITY: 'Total quantity is the sum of the not ready and ready quantities.',
  TOOLTIP_VIABILITY_TEST_AGAR_PETRI_DISH: 'A dish that contains a growth medium of solidified agar.',
  TOOLTIP_VIABILITY_TEST_CHEMICAL:
    'Treating seeds with a plant growth hormone or other chemical to break physiological dormancy.',
  TOOLTIP_VIABILITY_TEST_FRESH:
    'Seeds which were recently collected and have not been stored in the seed bank; recommended to establish a baseline of viability for a new accession.',
  TOOLTIP_VIABILITY_TEST_MEDIA_MIX:
    'A mix of substances through which roots grow and extract water and nutrients; may contain any of the media below.',
  TOOLTIP_VIABILITY_TEST_MOSS:
    'A small non-flowering, non-vascular plant which can be sterilized and used as a growth medium with high moisture retaining capacity.',
  TOOLTIP_VIABILITY_TEST_NURSERY_MEDIA:
    'A substance through which roots grow and extract water and nutrients in a pot, tray, or other nursery container.',
  TOOLTIP_VIABILITY_TEST_PAPER_PETRI_DISH: 'A dish that contains a growth medium of germination paper.',
  TOOLTIP_VIABILITY_TEST_PERLITE_VERMICULITE:
    'Lightweight sand substitutes for soilless potting mixes which are often used to improve aeration and texture in potting soil and garden soil mixtures.',
  TOOLTIP_VIABILITY_TEST_SAND_PETRI_DISH: 'A dish that contains a growth medium of sand.',
  TOOLTIP_VIABILITY_TEST_SAND:
    'A loose granular substance resulting from the erosion of siliceous and other rocks and forming a major constituent of beaches, riverbeds, the seabed, and deserts.',
  TOOLTIP_VIABILITY_TEST_SCARIFY:
    'Weakening, opening, or otherwise altering the seed coat to make it permeable to water, to break physical dormancy.',
  TOOLTIP_VIABILITY_TEST_SEED_TYPE: 'Condition of seeds to be tested for viability.',
  TOOLTIP_VIABILITY_TEST_SOAK:
    'A process of imbibing a seed by immersing the seed in water, to break physical dormancy.',
  TOOLTIP_VIABILITY_TEST_SOIL:
    'A black or dark brown material typically consisting of a mixture of organic remains, clay, and rock particles.',
  TOOLTIP_VIABILITY_TEST_STORED:
    'Seeds which have been stored for any length of time; recommended to monitor viability over time in order to use seeds before viability is lost in storage.',
  TOOLTIP_VIABILITY_TEST_STRATIFICATION:
    'A process of exposing seeds to alternating temperatures, simulating natural conditions that seeds would experience, to break physiological dormancy.',
  TOOLTIP_VIABILITY_TEST_SUBSTRATE:
    'The surface or material that an organism lives, grows, or obtains its nourishment from.',
  TOOLTIP_VIABILITY_TEST_TREATMENT:
    'The biological, physical and chemical agents and techniques used to break dormancy and/or speed germination.',
  TOTAL_ACTIVE_ACCESSIONS: 'Total Active Accessions',
  TOTAL_ESTIMATED_PERCENTAGE_VIABILITY: 'Total Estimated % Viability',
  TOTAL_ESTIMATED_VIABILITY: 'Total Estimated Viability',
  TOTAL_NUMBER_OF_PLANTS: 'Total Number of Plants',
  TOTAL_OF_SEEDS_GERMINATED: 'Total of Seeds Germinated',
  TOTAL_QUANTITY: 'Total Quantity',
  TOTAL_READY_QUANTITY: 'Total Ready Quantity',
  TOTAL_SEED_COUNT: 'Total Seed Count',
  TOTAL_SEEDS_COUNT_ESTIMATION: 'Total Seeds Count Estimation',
  TOTAL_SEEDS_GERMINATED_ERROR: 'Germinated amount should not be more than tested amount.',
  TOTAL_SEEDS_GERMINATED: 'Total Seeds Germinated',
  TOTAL_SEEDS_TESTED_ERROR: 'Seeds tested should not be more than remaining seeds',
  TOTAL_SEEDS_TESTED: 'Total Seeds Tested',
  TOTAL_WEIGHT_OF_SEEDS: 'Total Weight of Seeds',
  TOTAL_WEIGHT: 'Total Weight ',
  TOTAL_WITHDRAW: 'Total Withdraw',
  TOTAL_WITHDRAWN: 'Total Withdrawn',
  TOTAL_WITHDRAWN_COUNT: 'Total Withdrawn (seeds)',
  TOTAL_WITHDRAWN_WEIGHT_GRAMS: 'Total Withdrawn (g)',
  TOTAL_WITHDRAWN_WEIGHT_KILOGRAMS: 'Total Withdrawn (kg)',
  TOTAL_WITHDRAWN_WEIGHT_MILLIGRAMS: 'Total Withdrawn (mg)',
  TOTAL_WITHDRAWN_WEIGHT_OUNCES: 'Total Withdrawn (oz)',
  TOTAL_WITHDRAWN_WEIGHT_POUNDS: 'Total Withdrawn (lb)',
  TOTAL_WITHDRAWN_WEIGHT_QUANTITY: 'Total Withdrawn Weight',
  TOTAL_WITHDRAWN_WEIGHT_UNITS: 'Total Withdrawn Weight Units',
  TOTAL: 'Total',
  TREATMENT: 'Treatment',
  TREE: 'Tree',
  TRY_AGAIN: 'Try Again',
  TURN_ON_END_DRYING_REMINDER: 'Turn on End-drying Reminder',
  TYPE_TO_SEARCH: 'Type to search...',
  TYPE: 'Type...',
  UNABLE_TO_ADD_PERSON: 'Unable to Add Person',
  UNABLE_TO_CONNECT_TO_SENSOR_KIT:
    'We were unable to connect to your sensor kit. Sometimes this is because it is not connected to power or internet. Please email {0} so we can assist you.',
  UNABLE_TO_LOAD_NOTIFICATIONS: 'Unable to load notifications. Try again later.',
  UNDO_SEND_TO_NURSERY: 'Undo Send to Nursery',
  UNEXPECTED_ERROR: 'An unexpected error occurred.',
  UNITS: 'Units',
  UNITS_INITIALIZED_MESSAGE: 'Your Weight System was updated to {0}. You can edit this setting from {1}.',
  UNITS_INITIALIZED_TITLE: 'Preferred weight system set',
  UNKNOWN: 'Unknown',
  UNSPECIFIED: 'Unspecified',
  UNSURE: 'Unsure',
  UPDATE_STATUS_WARNING: 'You‘re about to update the status',
  UPLOAD_PHOTO_DESCRIPTION: 'Browse or drag and drop a file (JPG, PNG).',
  UPLOAD_PHOTO_MOBILE_DESCRIPTION: 'Browse files (JPG, PNG).',
  UPLOAD_PHOTO: 'Upload Photo...',
  UPLOAD_PHOTOS: 'Upload Photo(s)',
  USED_UP: 'Used Up',
  VALUE_CANT_EXCEED_100: 'Value can’t exceed 100%',
  VIABILITY_RATE: 'Viability Rate',
  VIABILITY_RESULT: 'Viability Result',
  VIABILITY_START_DATE: 'Viability Start Date',
  VIABILITY_SUBSTRATE: 'Viability Substrate',
  VIABILITY_TEST_NUMBER: 'Viability Test (#{0})',
  VIABILITY_TEST_START_DATE_ERROR: 'This should not be before the date when seeds were collected',
  VIABILITY_TEST_TYPE: 'Viability Test Type',
  VIABILITY_TEST_TYPES_INFO: 'Selecting either one will unlock a new option on the sidebar after you save the changes.',
  VIABILITY_TEST_TYPES: 'Viability Test Types',
  VIABILITY_TEST: 'Viability Test',
  VIABILITY_TESTING_EMPTY_MESSAGE:
    'Viability Testing helps you track seed quality. You can conduct a nursery or lab germination test, or perform a cut test.',
  VIABILITY_TESTING_SECTION_TOOLTIP:
    'Each test will be listed separately, which may cause an accession to appear more than once in the table.',
  VIABILITY_TESTING: 'Viability Testing',
  VIABILITY_TESTS: 'Viability Tests',
  VIABILITY_TREATMENT: 'Viability Treatment',
  VIABILITY: 'Viability',
  VIEW_ACCESSION: 'View accession',
  VIEW_SITES_ZONES_PLOTS: 'View Sites, Zones, and Plots on a map.',
  VIEW: 'View',
  WAITING_TO_DOWNLOAD: 'Waiting to download...',
  WATTS_VALUE: '{0}W',
  WEIGHT_GRAMS: 'Weight (g)',
  WEIGHT_KILOGRAMS: 'Weight (kg)',
  WEIGHT_MILLIGRAMS: 'Weight (mg)',
  WEIGHT_OUNCES: 'Weight (oz)',
  WEIGHT_POUNDS: 'Weight (lb)',
  WEIGHT_UNITS: 'Weight Units',
  WEIGHT_TO_COUNT_CALCULATOR: 'Weight to Count Calculator',
  WELCOME_MSG: 'Welcome and happy seeding!',
  WELCOME_PERSON: 'Welcome, {0}!',
  WELCOME: 'Welcome!',
  WILD_IN_SITU_DESCRIPTION: 'Plants that occur naturally in wild areas and were not planted by people.',
  WILD_IN_SITU: 'Wild (In Situ)',
  WILD: 'Wild',
  WITH_MAP: 'With Map',
  WITHDRAW_ALL: 'Withdraw all',
  WITHDRAW_DATE_REQUIRED: 'Withdraw Date *',
  WITHDRAW_FROM_BATCHES: 'Withdraw from Batches',
  WITHDRAW_INSTRUCTIONS: 'Select a withdrawal purpose and enter the quantities from each batch to withdraw.',
  WITHDRAW_QUANTITY_REQUIRED: 'Withdraw Quantity *',
  WITHDRAW_QUANTITY: 'Withdraw Quantity',
  WITHDRAW_REMAINING_SEEDS: 'Withdraw All Remaining Seeds',
  WITHDRAW_SEEDLINGS: 'Withdraw Seedlings',
  WITHDRAW_SEEDS: 'Withdraw Seeds',
  WITHDRAW: 'Withdraw',
  WITHDRAWAL_BATCHES_MISSING_QUANTITY_ERROR: 'Enter a quantity in at least one seedlings batch row.',
  WITHDRAWAL_DESCRIPTION: 'All the details about withdrawal of the seeds.',
  WITHDRAWAL_DETAILS: 'Withdrawal Details',
  WITHDRAWAL_LOG: 'Withdrawal Log',
  WITHDRAWAL: 'Withdrawal',
  WITHDRAWN_BY: 'Withdrawn By',
  WITHDRAWN_DATE: 'Withdrawn Date',
  WITHDRAWN_ON: 'Withdrawn On',
  WITHDRAWN_QUANTITY_ERROR: 'Exceeds remaining quantity',
  WITHDRAWN: 'Withdrawn',
  WITHOUT_MAP: 'Without Map',
  YES: 'Yes',
  ZERO: 'zero',
  ZONE_REQUIRED: 'Zone *',
  ZONE: 'Zone',
};
