export enum QueryTagTypes {
  AcceleratorProjects = 'AcceleratorProjects',
  DraftPlantingSites = 'DraftPlantingSites',
  Funders = 'Funders',
  FundingEntities = 'FundingEntities',
  Modules = 'Modules',
  Notifications = 'Notifications',
  Observation = 'Observation',
  ObservationMedia = 'ObservationMedia',
  ObservationSplats = 'ObservationSplats',
  PlantingSites = 'PlantingSites',
  ProjectInternalUsers = 'ProjectInternalUsers',
  ProjectMetricTargets = 'ProjectMetricTargets',
  ProjectMetrics = 'ProjectMetrics',
  ProjectModules = 'ProjectModules',
  ProjectReportConfigs = 'ProjectReportConfigs',
  Projects = 'Projects',
  PublishedReportMedia = 'PublishedReportMedia',
  PublishedReports = 'PublishedReports',
  ReportMedia = 'ReportMedia',
  Reports = 'Reports',
  StandadMetricTargets = 'StandadMetricTargets',
  StandardMetrics = 'StandadMetrics',
  SystemMetricTargets = 'SystemMetricTargets',
  SystemMetrics = 'SystemMetrics',
  T0 = 'T0',
}

export const QUERY_TAGS = Object.values(QueryTagTypes);
