export enum QueryTagTypes {
  AcceleratorProjects = 'AcceleratorProjects',
  Activities = 'Activities',
  Deliveries = 'Deliveries',
  FunderActivities = 'FunderActivities',
  CommonIndicators = 'CommonIndicators',
  ProjectIndicators = 'ProjectIndicators',
  DraftPlantingSites = 'DraftPlantingSites',
  Funders = 'Funders',
  FundingEntities = 'FundingEntities',
  Modules = 'Modules',
  Notifications = 'Notifications',
  NurseryWithdrawalPhotos = 'NurseryWithdrawalPhotos',
  NurseryWithdrawals = 'NurseryWithdrawals',
  Observation = 'Observation',
  ObservationMedia = 'ObservationMedia',
  OrganizationMedia = 'OrganizationMedia',
  ObservationSplats = 'ObservationSplats',
  PlantingSites = 'PlantingSites',
  ProjectInternalUsers = 'ProjectInternalUsers',
  ProjectModules = 'ProjectModules',
  ProjectReportConfigs = 'ProjectReportConfigs',
  Projects = 'Projects',
  PublishedReportMedia = 'PublishedReportMedia',
  PublishedReports = 'PublishedReports',
  ReportMedia = 'ReportMedia',
  Reports = 'Reports',
  T0 = 'T0',
}

export const QUERY_TAGS = Object.values(QueryTagTypes);
