/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/accounts/me": {
    get: operations["read_accounts_me_api_v1_accounts_me_get"];
  };
  "/api/v1/features": {
    get: operations["read_feature_list_api_v1_features_get"];
    post: operations["create_feature_api_v1_features_post"];
  };
  "/api/v1/features/{feature_id}": {
    get: operations["read_feature_api_v1_features__feature_id__get"];
    put: operations["update_feature_api_v1_features__feature_id__put"];
    delete: operations["delete_feature_api_v1_features__feature_id__delete"];
  };
  "/api/v1/layers": {
    get: operations["read_layer_list_api_v1_layers_get"];
    post: operations["create_item_api_v1_layers_post"];
  };
  "/api/v1/organizations": {
    get: operations["read_organization_list_api_v1_organizations_get"];
    post: operations["create_organization_api_v1_organizations_post"];
  };
  "/api/v1/organizations/{organization_id}": {
    get: operations["read_organization_api_v1_organizations__organization_id__get"];
    put: operations["update_organization_api_v1_organizations__organization_id__put"];
  };
  "/api/v1/photos": {
    get: operations["read_photo_list_api_v1_photos_get"];
    post: operations["create_photo_api_v1_photos_post"];
  };
  "/api/v1/photos/{photo_id}": {
    get: operations["read_photo_api_v1_photos__photo_id__get"];
    delete: operations["delete_photo_api_v1_photos__photo_id__delete"];
  };
  "/api/v1/plants": {
    get: operations["read_plant_list_api_v1_plants_get"];
    post: operations["create_item_api_v1_plants_post"];
  };
  "/api/v1/plants/{feature_id}": {
    get: operations["read_plant_api_v1_plants__feature_id__get"];
    put: operations["update_plant_api_v1_plants__feature_id__put"];
    delete: operations["delete_plant_api_v1_plants__feature_id__delete"];
  };
  "/api/v1/plant_observations": {
    get: operations["read_plant_observation_list_api_v1_plant_observations_get"];
    post: operations["create_item_api_v1_plant_observations_post"];
  };
  "/api/v1/tiles/{site_id}/{file_path}": {
    get: operations["read_tile_api_v1_tiles__site_id___file_path__get"];
  };
  "/api/v1/accounts": {
    get: operations["read_item_list_api_v1_accounts_get"];
    post: operations["create_item_api_v1_accounts_post"];
  };
  "/api/v1/accounts/{item_id}": {
    get: operations["read_item_api_v1_accounts__item_id__get"];
    put: operations["update_item_api_v1_accounts__item_id__put"];
    delete: operations["delete_item_api_v1_accounts__item_id__delete"];
  };
  "/api/v1/organization_accounts": {
    get: operations["read_item_list_api_v1_organization_accounts_get"];
    post: operations["create_item_api_v1_organization_accounts_post"];
  };
  "/api/v1/organization_accounts/{item_id}": {
    get: operations["read_item_api_v1_organization_accounts__item_id__get"];
    put: operations["update_item_api_v1_organization_accounts__item_id__put"];
    delete: operations["delete_item_api_v1_organization_accounts__item_id__delete"];
  };
  "/api/v1/projects": {
    get: operations["read_item_list_api_v1_projects_get"];
    post: operations["create_item_api_v1_projects_post"];
  };
  "/api/v1/projects/{item_id}": {
    get: operations["read_item_api_v1_projects__item_id__get"];
    put: operations["update_item_api_v1_projects__item_id__put"];
    delete: operations["delete_item_api_v1_projects__item_id__delete"];
  };
  "/api/v1/sites": {
    get: operations["read_item_list_api_v1_sites_get"];
    post: operations["create_item_api_v1_sites_post"];
  };
  "/api/v1/sites/{item_id}": {
    get: operations["read_item_api_v1_sites__item_id__get"];
    put: operations["update_item_api_v1_sites__item_id__put"];
    delete: operations["delete_item_api_v1_sites__item_id__delete"];
  };
  "/api/v1/layers/{item_id}": {
    get: operations["read_item_api_v1_layers__item_id__get"];
    put: operations["update_item_api_v1_layers__item_id__put"];
    delete: operations["delete_item_api_v1_layers__item_id__delete"];
  };
  "/api/v1/plants/{item_id}": {
    get: operations["read_item_api_v1_plants__item_id__get"];
    put: operations["update_item_api_v1_plants__item_id__put"];
    delete: operations["delete_item_api_v1_plants__item_id__delete"];
  };
  "/api/v1/plant_observations/{item_id}": {
    get: operations["read_item_api_v1_plant_observations__item_id__get"];
    put: operations["update_item_api_v1_plant_observations__item_id__put"];
    delete: operations["delete_item_api_v1_plant_observations__item_id__delete"];
  };
  "/api/v1/species": {
    get: operations["read_item_list_api_v1_species_get"];
    post: operations["create_item_api_v1_species_post"];
  };
  "/api/v1/species/{item_id}": {
    get: operations["read_item_api_v1_species__item_id__get"];
    put: operations["update_item_api_v1_species__item_id__put"];
    delete: operations["delete_item_api_v1_species__item_id__delete"];
  };
  "/api/v1/species_names": {
    get: operations["read_item_list_api_v1_species_names_get"];
    post: operations["create_item_api_v1_species_names_post"];
  };
  "/api/v1/species_names/{item_id}": {
    get: operations["read_item_api_v1_species_names__item_id__get"];
    put: operations["update_item_api_v1_species_names__item_id__put"];
    delete: operations["delete_item_api_v1_species_names__item_id__delete"];
  };
  "/api/v1/account_roles": {
    get: operations["read_item_list_api_v1_account_roles_get"];
    post: operations["create_item_api_v1_account_roles_post"];
  };
  "/api/v1/account_roles/{item_id}": {
    get: operations["read_item_api_v1_account_roles__item_id__get"];
    put: operations["update_item_api_v1_account_roles__item_id__put"];
    delete: operations["delete_item_api_v1_account_roles__item_id__delete"];
  };
  "/api/v1/project_types": {
    get: operations["read_item_list_api_v1_project_types_get"];
    post: operations["create_item_api_v1_project_types_post"];
  };
  "/api/v1/project_types/{item_id}": {
    get: operations["read_item_api_v1_project_types__item_id__get"];
    put: operations["update_item_api_v1_project_types__item_id__put"];
    delete: operations["delete_item_api_v1_project_types__item_id__delete"];
  };
  "/api/v1/project_statuses": {
    get: operations["read_item_list_api_v1_project_statuses_get"];
    post: operations["create_item_api_v1_project_statuses_post"];
  };
  "/api/v1/project_statuses/{item_id}": {
    get: operations["read_item_api_v1_project_statuses__item_id__get"];
    put: operations["update_item_api_v1_project_statuses__item_id__put"];
    delete: operations["delete_item_api_v1_project_statuses__item_id__delete"];
  };
  "/api/v1/layer_types": {
    get: operations["read_item_list_api_v1_layer_types_get"];
    post: operations["create_item_api_v1_layer_types_post"];
  };
  "/api/v1/layer_types/{item_id}": {
    get: operations["read_item_api_v1_layer_types__item_id__get"];
    put: operations["update_item_api_v1_layer_types__item_id__put"];
    delete: operations["delete_item_api_v1_layer_types__item_id__delete"];
  };
  "/api/v1/health_states": {
    get: operations["read_item_list_api_v1_health_states_get"];
    post: operations["create_item_api_v1_health_states_post"];
  };
  "/api/v1/health_states/{item_id}": {
    get: operations["read_item_api_v1_health_states__item_id__get"];
    put: operations["update_item_api_v1_health_states__item_id__put"];
    delete: operations["delete_item_api_v1_health_states__item_id__delete"];
  };
  "/api/v1/token": {
    post: operations["login_api_v1_token_post"];
  };
  "/": {
    get: operations["test_page__get"];
  };
  "/test": {
    get: operations["test_page_test_get"];
  };
}

export interface components {
  schemas: {
    Account: {
      id?: number;
      auth_id: string;
      super_admin: boolean;
      created_time?: string;
      modified_time?: string;
    };
    AccountRole: {
      id: number;
      name: string;
    };
    Body_create_photo_api_v1_photos_post: {
      file: string;
    };
    Body_login_api_v1_token_post: {
      grant_type?: string;
      username: string;
      password: string;
      scope?: string;
      client_id?: string;
      client_secret?: string;
    };
    Feature: {
      id?: number;
      layer_id: number;
      shape_type_id: number;
      geom?: { [key: string]: unknown };
      altitude?: number;
      gps_horiz_accuracy?: number;
      gps_vert_accuracy?: number;
      attrib?: string;
      notes?: string;
      entered_time?: string;
      created_time?: string;
      modified_time?: string;
    };
    HTTPValidationError: {
      detail?: components["schemas"]["ValidationError"][];
    };
    HealthState: {
      id: number;
      name: string;
    };
    Layer: {
      id?: number;
      site_id: number;
      type_id: number;
      tile_set_name?: string;
      proposed: boolean;
      hidden: boolean;
      deleted: boolean;
      created_time?: string;
      modified_time?: string;
    };
    LayerType: {
      id: number;
      name: string;
    };
    Organization: {
      id?: number;
      name: string;
      location?: string;
      created_time?: string;
      modified_time?: string;
      disabled_time?: string;
    };
    OrganizationAccount: {
      id?: number;
      account_id: number;
      organization_id: number;
      role_id: number;
      created_time?: string;
      modified_time?: string;
    };
    Plant: {
      feature_id: number;
      label?: string;
      species_id?: number;
      natural_regen?: boolean;
      date_planted?: string;
      created_time?: string;
      modified_time?: string;
    };
    PlantObservation: {
      id?: number;
      feature_id?: number;
      timestamp: string;
      health_state_id?: number;
      flowers?: boolean;
      seeds?: boolean;
      pests?: string;
      height?: number;
      dbh?: number;
      created_time?: string;
      modified_time?: string;
    };
    Project: {
      id?: number;
      organization_id: number;
      name: string;
      description?: string;
      location?: string;
      type_id?: number;
      status_id?: number;
      start_date?: string;
      end_date?: string;
      pm_account_id?: number;
      created_time?: string;
      modified_time?: string;
      disabled_time?: string;
    };
    ProjectStatus: {
      id: number;
      name: string;
    };
    ProjectType: {
      id: number;
      name: string;
    };
    Site: {
      id?: number;
      project_id: number;
      name: string;
      locale?: string;
      timezone?: string;
      hectares?: number;
      origin?: string;
      created_time?: string;
      modified_time?: string;
      disabled_time?: string;
    };
    Species: {
      id?: number;
      family_id?: number;
      scientific_name?: string;
      created_time?: string;
      modified_time?: string;
      endangered_type_id?: number;
      rare_type_id?: number;
    };
    SpeciesName: {
      id?: number;
      species_id: number;
      organization_id?: number;
      name: string;
      is_scientific?: boolean;
      locale?: string;
      created_time?: string;
      modified_time?: string;
    };
    ValidationError: {
      loc: string[];
      msg: string;
      type: string;
    };
  };
}

export interface operations {
  read_accounts_me_api_v1_accounts_me_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  read_feature_list_api_v1_features_get: {
    parameters: {
      query: {
        layer_id: number;
        skip?: number;
        limit?: number;
        crs?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_feature_api_v1_features_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Feature"];
      };
    };
  };
  read_feature_api_v1_features__feature_id__get: {
    parameters: {
      path: {
        feature_id: number;
      };
      query: {
        crs?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_feature_api_v1_features__feature_id__put: {
    parameters: {
      path: {
        feature_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Feature"];
      };
    };
  };
  delete_feature_api_v1_features__feature_id__delete: {
    parameters: {
      path: {
        feature_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_layer_list_api_v1_layers_get: {
    parameters: {
      query: {
        site_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_item_api_v1_layers_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Layer"];
      };
    };
  };
  read_organization_list_api_v1_organizations_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_organization_api_v1_organizations_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Organization"];
      };
    };
  };
  read_organization_api_v1_organizations__organization_id__get: {
    parameters: {
      path: {
        organization_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_organization_api_v1_organizations__organization_id__put: {
    parameters: {
      path: {
        organization_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Organization"];
      };
    };
  };
  read_photo_list_api_v1_photos_get: {
    parameters: {
      query: {
        feature_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_photo_api_v1_photos_post: {
    parameters: {
      query: {
        feature_id: number;
        captured_time: string;
        heading?: number;
        orientation?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_create_photo_api_v1_photos_post"];
      };
    };
  };
  read_photo_api_v1_photos__photo_id__get: {
    parameters: {
      path: {
        photo_id: number;
      };
      query: {
        image: boolean;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_photo_api_v1_photos__photo_id__delete: {
    parameters: {
      path: {
        photo_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_plant_list_api_v1_plants_get: {
    parameters: {
      query: {
        layer_id: number;
        species_name?: string;
        min_entered_time?: string;
        max_entered_time?: string;
        notes?: string;
        summary?: boolean;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_item_api_v1_plants_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Plant"];
      };
    };
  };
  read_plant_api_v1_plants__feature_id__get: {
    parameters: {
      path: {
        feature_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_plant_api_v1_plants__feature_id__put: {
    parameters: {
      path: {
        feature_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Plant"];
      };
    };
  };
  delete_plant_api_v1_plants__feature_id__delete: {
    parameters: {
      path: {
        feature_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_plant_observation_list_api_v1_plant_observations_get: {
    parameters: {
      query: {
        plant_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_item_api_v1_plant_observations_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlantObservation"];
      };
    };
  };
  read_tile_api_v1_tiles__site_id___file_path__get: {
    parameters: {
      path: {
        site_id: number;
        file_path: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_accounts_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_accounts_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Account"];
      };
    };
  };
  read_item_api_v1_accounts__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_accounts__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Account"];
      };
    };
  };
  delete_item_api_v1_accounts__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_organization_accounts_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_organization_accounts_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationAccount"];
      };
    };
  };
  read_item_api_v1_organization_accounts__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_organization_accounts__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OrganizationAccount"];
      };
    };
  };
  delete_item_api_v1_organization_accounts__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_projects_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_projects_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Project"];
      };
    };
  };
  read_item_api_v1_projects__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_projects__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Project"];
      };
    };
  };
  delete_item_api_v1_projects__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_sites_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_sites_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Site"];
      };
    };
  };
  read_item_api_v1_sites__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_sites__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Site"];
      };
    };
  };
  delete_item_api_v1_sites__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_api_v1_layers__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_layers__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Layer"];
      };
    };
  };
  delete_item_api_v1_layers__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_api_v1_plants__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_plants__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Plant"];
      };
    };
  };
  delete_item_api_v1_plants__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_api_v1_plant_observations__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_plant_observations__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlantObservation"];
      };
    };
  };
  delete_item_api_v1_plant_observations__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_species_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_species_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Species"];
      };
    };
  };
  read_item_api_v1_species__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_species__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Species"];
      };
    };
  };
  delete_item_api_v1_species__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_species_names_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_species_names_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SpeciesName"];
      };
    };
  };
  read_item_api_v1_species_names__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_species_names__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SpeciesName"];
      };
    };
  };
  delete_item_api_v1_species_names__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_account_roles_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_account_roles_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountRole"];
      };
    };
  };
  read_item_api_v1_account_roles__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_account_roles__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountRole"];
      };
    };
  };
  delete_item_api_v1_account_roles__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_project_types_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_project_types_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectType"];
      };
    };
  };
  read_item_api_v1_project_types__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_project_types__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectType"];
      };
    };
  };
  delete_item_api_v1_project_types__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_project_statuses_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_project_statuses_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectStatus"];
      };
    };
  };
  read_item_api_v1_project_statuses__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_project_statuses__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectStatus"];
      };
    };
  };
  delete_item_api_v1_project_statuses__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_layer_types_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_layer_types_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LayerType"];
      };
    };
  };
  read_item_api_v1_layer_types__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_layer_types__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LayerType"];
      };
    };
  };
  delete_item_api_v1_layer_types__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_item_list_api_v1_health_states_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  create_item_api_v1_health_states_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HealthState"];
      };
    };
  };
  read_item_api_v1_health_states__item_id__get: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_item_api_v1_health_states__item_id__put: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HealthState"];
      };
    };
  };
  delete_item_api_v1_health_states__item_id__delete: {
    parameters: {
      path: {
        item_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_v1_token_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_token_post"];
      };
    };
  };
  test_page__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  test_page_test_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
}

export interface external {}
