import { test } from '@playwright/test';

import AccessionTests from './accession.spec';
import DeliverableTests from './deliverables.spec';
import FunderProjectProfileTests from './funderProjectProfile.spec';
import FundingEntitiesTests from './fundingEntities.spec';
import InventoryTests from './inventory.spec';
import LocationTests from './locations.spec';
import MatrixViewTests from './matrixView.spec';
import ObservationDetailsTests from './observationDetails.spec';
import ObservationTests from './observations.spec';
import ParticipantPlantsDashboardTests from './participantPlantsDashboard.spec';
import PlantsDashboardTests from './plantsDashboard.spec';
import ProjectDeliverablesTests from './projectDeliverables.spec';
import ProjectDocumentsTests from './projectDocuments.spec';
import ProjectProfileTests from './projectProfile.spec';
import ProjectVariablesTests from './projectVariables.spec';
import SpeciesTests from './species.spec';

test.describe(LocationTests);
test.describe(SpeciesTests);
test.describe(AccessionTests);
test.describe(InventoryTests);
test.describe(ProjectProfileTests);
test.describe(FunderProjectProfileTests);
test.describe(FundingEntitiesTests);
test.describe(PlantsDashboardTests);
test.describe(ProjectDeliverablesTests);
test.describe(ProjectDocumentsTests);
test.describe(ProjectVariablesTests);
test.describe(ParticipantPlantsDashboardTests);
test.describe(ObservationTests);
test.describe(ObservationDetailsTests);
test.describe(DeliverableTests);
test.describe(MatrixViewTests);
