#!/bin/bash
#
# Set environment variables that can be consumed by commands. This is run after plugins
# such as the AWS Secrets Manager plugin, so it can refer to any environment variables
# set by those plugins.
#
# The Buildkite agent effectively sources this file in bash before launching commands,
# so any environment variables exported here will be available to all commands. See
# https://buildkite.com/docs/agent/hooks for more details.
#

set -euo pipefail

COMMIT_SHA="${BUILDKITE_COMMIT:0:12}"

# Define tier and app version based on branch/tag
if [[ "${BUILDKITE_TAG:-}" =~ ^v[0-9]+\.[0-9.]+ ]]; then
    TIER=PROD
    IS_CD=true
    APP_VERSION="${BUILDKITE_TAG}"
elif [[ "${BUILDKITE_BRANCH}" == "main" ]]; then
    TIER=STAGING
    IS_CD=true
    APP_VERSION="x${COMMIT_SHA}"
else
    TIER=CI
    IS_CD=false
    APP_VERSION="${COMMIT_SHA}"
fi

LOWER_TIER=$(echo "$TIER" | tr '[:upper:]' '[:lower:]')

# If this commit's title has a suffix like (#123), it's probably a merged PR.
MERGED_PR_NUMBER=$(git log -1 --pretty=%s | sed -En 's/.*\(#([0-9]+)\)$/\1/p')

export APP_VERSION
export COMMIT_SHA
export IS_CD
export LOWER_TIER
export MERGED_PR_NUMBER
export TIER
