export const API_PULL_INTERVAL = 60000;
export const TERRAWARE_SUPPORT_LINK = 'https://www.terraformation.com/contact-us/terraware-support';

export enum APP_PATHS {
  ACCESSIONS = '/accessions',
  ACCESSIONS_NEW = '/accessions/new',
  ACCESSIONS_ITEM_SEED_COLLECTION = '/accessions/:accessionId/seed-collection',
  ACCESSIONS_ITEM_PROCESSING_DRYING = '/accessions/:accessionId/processing-drying',
  ACCESSIONS_ITEM_STORAGE = '/accessions/:accessionId/storage',
  ACCESSIONS_ITEM_WITHDRAWAL = '/accessions/:accessionId/withdrawal',
  ACCESSIONS_ITEM_NURSERY = '/accessions/:accessionId/nursery',
  ACCESSIONS_ITEM_LAB = '/accessions/:accessionId/lab',
  ACCESSIONS_ITEM = '/accessions/:accessionId',
  CHECKIN = '/checkin',
  CONTACT_US = '/contactus',
  ERROR = '/error',
  ERROR_MOBILE_NOT_SUPPORTED = '/error/mobile-not-supported',
  ERROR_FAILED_TO_FETCH_ORG_DATA = '/error/cannot-fetch-org-data',
  HOME = '/home',
  ORGANIZATION_EDIT = '/organization/edit',
  ORGANIZATION = '/organization',
  PEOPLE_NEW = '/people/new',
  PEOPLE_EDIT = '/people/:personId/edit',
  PEOPLE_VIEW = '/people/:personId',
  PEOPLE = '/people',
  PROJECTS_NEW = '/projects/new',
  PROJECTS_EDIT = '/projects/:projectId/edit',
  PROJECTS_VIEW = '/projects/:projectId',
  PROJECTS = '/projects',
  SEEDS_DASHBOARD = '/seeds-dashboard',
  SITES_NEW = '/sites/new',
  SITES_EDIT = '/sites/:siteId/edit',
  SITES_VIEW = '/sites/:siteId',
  SITES = '/sites',
  SPECIES = '/species',
  WELCOME = '/welcome',
}
