export const API_PULL_INTERVAL = 60000;

export enum APP_PATHS {
  ACCESSIONS = '/accessions',
  ACCESSIONS_NEW = '/accessions/new',
  ACCESSIONS_ITEM_SEED_COLLECTION = '/accessions/:accessionId/seed-collection',
  ACCESSIONS_ITEM_PROCESSING_DRYING = '/accessions/:accessionId/processing-drying',
  ACCESSIONS_ITEM_STORAGE = '/accessions/:accessionId/storage',
  ACCESSIONS_ITEM_WITHDRAWAL = '/accessions/:accessionId/withdrawal',
  ACCESSIONS_ITEM_NURSERY = '/accessions/:accessionId/nursery',
  ACCESSIONS_ITEM_LAB = '/accessions/:accessionId/lab',
  ACCESSIONS_ITEM = '/accessions/:accessionId',
  CHECKIN = '/checkin',
  CONTACT_US = '/contactus',
  ERROR = '/error',
  HOME = '/home',
  ORGANIZATION_EDIT = '/organization/edit',
  ORGANIZATION = '/organization',
  PEOPLE_NEW = '/people/new',
  PEOPLE_ID = '/people/:personId',
  PEOPLE = '/people',
  PLANTS_DASHBOARD = '/plants-dashboard',
  PLANTS_LIST = '/plants-list',
  PROJECTS_NEW = '/projects/new',
  PROJECTS_EDIT = '/projects/:projectId/edit',
  PROJECTS_VIEW = '/projects/:projectId',
  PROJECTS = '/projects',
  SEEDS_DASHBOARD = '/seeds-summary',
  SITES_NEW = '/sites/new',
  SITES_EDIT = '/sites/:siteId/edit',
  SITES_VIEW = '/sites/:siteId',
  SITES = '/sites',
  SPECIES = '/species',
  WELCOME = '/welcome',
}
